packages:
  - .
minimumReleaseAgeExclude:
  - '@vielzeug/arsenal@1.1.2'
  - '@vielzeug/clockwork@1.1.1'
  - '@vielzeug/coins@1.0.4'
  - '@vielzeug/courier@1.1.4'
  - '@vielzeug/dnd@1.2.2'
  - '@vielzeug/familiar@1.0.5'
  - '@vielzeug/flux@1.0.7'
  - '@vielzeug/herald@1.0.4'
  - '@vielzeug/keymap@1.1.2'
  - '@vielzeug/ledger@1.1.5'
  - '@vielzeug/lingua@1.1.3'
  - '@vielzeug/orbit@1.1.2'
  - '@vielzeug/ore@1.2.3'
  - '@vielzeug/prism@1.1.6'
  - '@vielzeug/pulse@1.0.7'
  - '@vielzeug/refine@1.7.0'
  - '@vielzeug/ripple@1.2.3'
  - '@vielzeug/rune@1.1.2'
  - '@vielzeug/scout@1.1.6'
  - '@vielzeug/scroll@1.1.3'
  - '@vielzeug/sourcerer@1.0.6'
  - '@vielzeug/spell@1.2.1'
  - '@vielzeug/tempo@1.0.4'
  - '@vielzeug/vault@1.0.4'
  - '@vielzeug/ward@1.0.5'
  - '@vielzeug/wayfinder@1.0.4'
