import type { Board, User } from './types';

export const seedUsers: User[] = [
  { id: 'user-alice', name: 'Alice Chen', role: 'admin' },
  { id: 'user-bob', name: 'Bob Martinez', role: 'member' },
  { id: 'user-carol', name: 'Carol Singh', role: 'member' },
  { id: 'user-dave', name: 'Dave Kim', role: 'viewer' },
];

export const seedBoard: Board = {
  columns: [
    { id: 'todo', title: 'To Do' },
    { id: 'in-progress', title: 'In Progress', wipLimit: 3 },
    { id: 'review', title: 'Review' },
    { id: 'done', title: 'Done' },
  ],
  tasks: [
    {
      assigneeId: 'user-alice',
      budget: null,
      description: 'Agree on REST endpoints and JSON shapes for the backend team.',
      dueDate: '2026-07-20',
      id: 'task-001',
      ownerId: 'user-alice',
      priority: 'high',
      status: 'todo',
      title: 'Define API contract',
    },
    {
      assigneeId: 'user-bob',
      budget: { amount: '500.00', currency: 'USD' },
      description: 'Configure GitHub Actions for lint, test, and build steps.',
      dueDate: '2026-07-18',
      id: 'task-002',
      ownerId: 'user-alice',
      priority: 'medium',
      status: 'todo',
      title: 'Set up CI pipeline',
    },
    {
      assigneeId: null,
      budget: null,
      description: 'Create a getting-started guide for new contributors.',
      dueDate: null,
      id: 'task-003',
      ownerId: 'user-carol',
      priority: 'low',
      status: 'todo',
      title: 'Write onboarding docs',
    },
    {
      assigneeId: 'user-bob',
      budget: { amount: '1200.00', currency: 'USD' },
      description: 'Add JWT-based login and refresh-token flow.',
      dueDate: '2026-07-15',
      id: 'task-004',
      ownerId: 'user-alice',
      priority: 'urgent',
      status: 'in-progress',
      title: 'Implement authentication',
    },
    {
      assigneeId: 'user-carol',
      budget: { amount: '800.00', currency: 'USD' },
      description: 'Wire up the @vielzeug/dnd primitives to allow card reordering.',
      dueDate: '2026-07-22',
      id: 'task-005',
      ownerId: 'user-alice',
      priority: 'high',
      status: 'in-progress',
      title: 'Build kanban drag-and-drop',
    },
    {
      assigneeId: 'user-alice',
      budget: { amount: '350.00', currency: 'USD' },
      description: 'Use @vielzeug/coins for precise monetary arithmetic on task budgets.',
      dueDate: '2026-07-25',
      id: 'task-006',
      ownerId: 'user-alice',
      priority: 'medium',
      status: 'in-progress',
      title: 'Integrate budget tracking',
    },
    {
      assigneeId: 'user-carol',
      budget: null,
      description: 'Run axe-core against all components and fix reported violations.',
      dueDate: '2026-07-14',
      id: 'task-007',
      ownerId: 'user-bob',
      priority: 'high',
      status: 'review',
      title: 'Accessibility audit',
    },
    {
      assigneeId: 'user-bob',
      budget: { amount: '600.00', currency: 'USD' },
      description: 'Profile the virtual list with 10 000 tasks and address bottlenecks.',
      dueDate: '2026-07-16',
      id: 'task-008',
      ownerId: 'user-alice',
      priority: 'medium',
      status: 'review',
      title: 'Performance profiling',
    },
    {
      assigneeId: 'user-alice',
      budget: null,
      description: 'Add a CSS custom-property theme layer for light and dark palettes.',
      dueDate: null,
      id: 'task-009',
      ownerId: 'user-carol',
      priority: 'low',
      status: 'review',
      title: 'Dark mode support',
    },
    {
      assigneeId: 'user-carol',
      budget: { amount: '400.00', currency: 'USD' },
      description: 'Export spacing, colour, and typography tokens as CSS variables.',
      dueDate: '2026-07-05',
      id: 'task-010',
      ownerId: 'user-alice',
      priority: 'medium',
      status: 'done',
      title: 'Design system tokens',
    },
    {
      assigneeId: 'user-alice',
      budget: null,
      description: 'Configure Rush, pnpm workspaces, and shared ESLint / Prettier configs.',
      dueDate: '2026-07-01',
      id: 'task-011',
      ownerId: 'user-alice',
      priority: 'low',
      status: 'done',
      title: 'Set up monorepo tooling',
    },
    {
      assigneeId: 'user-bob',
      budget: { amount: '250.00', currency: 'USD' },
      description: 'Cover ripple signals and forge form-state with Vitest.',
      dueDate: '2026-07-08',
      id: 'task-012',
      ownerId: 'user-bob',
      priority: 'medium',
      status: 'done',
      title: 'Write unit tests for state layer',
    },
  ],
};
