import { assert } from '../function/assert';
import { IS_ARRAY_ERROR_MSG, isArray } from '../typed/isArray';
import type { Selector } from '../types';

/**
 * Aggregates an array of objects into an object based on a key generated by a selector function.
 *
 * @example
 * ```ts
 * const data = [{ a: 1 }, { a: 2 }, { a: 1 }];
 * aggregate(data, 'a') // { '1': { a: 1 }, '2': { a: 2 } };
 * ```
 *
 * @param array - The array to key.
 * @param selector - The function to generate the key for each element. It can be a string representing the key or a function that returns the key.
 *
 * @returns An object with keys as the generated values and values as the last element responsible for generating the key.
 *
 * @throws {TypeError} If the provided array is not an array.
 */
export function aggregate<T, K extends keyof T, R extends T[K] extends string ? T[K] : never>(
  array: T[],
  selector: Selector<T>,
): Record<R, T> {
  assert(isArray(array), IS_ARRAY_ERROR_MSG, { args: { array }, type: TypeError });

  const result = {} as Record<R, T>;
  const getKey = typeof selector === 'function' ? selector : (item: T) => item[selector];

  for (let index = 0; index < array.length; index++) {
    const item = array[index];
    const key = getKey(item) as R;

    result[key] = item;
  }

  return result;
}

aggregate.fp = true;
