export const SYSTEM_DATA = {
  cronExpressions: [
    '0 * * * *',
    '0 0 * * *',
    '0 0 * * 0',
    '*/5 * * * *',
    '0 12 * * 1-5',
    '0 0 1 * *',
    '0 0 1 1 *',
    '0 3 * * *',
    '30 7 * * 1-5',
    '0 18 * * 5',
  ],
  directories: [
    'src',
    'dist',
    'build',
    'lib',
    'test',
    'docs',
    'config',
    'assets',
    'public',
    'private',
    'tmp',
    'cache',
    'var',
    'opt',
    'etc',
  ],
  fileExtensions: [
    'txt',
    'pdf',
    'doc',
    'docx',
    'xls',
    'xlsx',
    'ppt',
    'pptx',
    'jpg',
    'png',
    'gif',
    'svg',
    'webp',
    'ico',
    'mp3',
    'wav',
    'flac',
    'ogg',
    'mp4',
    'avi',
    'mkv',
    'webm',
    'zip',
    'tar',
    'gz',
    'rar',
    '7z',
    'js',
    'ts',
    'json',
    'xml',
    'html',
    'css',
    'md',
    'py',
    'java',
    'go',
    'rs',
    'c',
    'cpp',
  ],
  fileNames: [
    'document',
    'report',
    'summary',
    'notes',
    'draft',
    'config',
    'readme',
    'index',
    'main',
    'app',
    'data',
    'backup',
    'export',
    'import',
    'log',
  ],
  mimeTypes: {
    avi: 'video/x-msvideo',
    css: 'text/css',
    gif: 'image/gif',
    gz: 'application/gzip',
    html: 'text/html',
    jpeg: 'image/jpeg',
    jpg: 'image/jpeg',
    js: 'application/javascript',
    json: 'application/json',
    mp3: 'audio/mpeg',
    mp4: 'video/mp4',
    pdf: 'application/pdf',
    png: 'image/png',
    svg: 'image/svg+xml',
    tar: 'application/x-tar',
    txt: 'text/plain',
    wav: 'audio/wav',
    webp: 'image/webp',
    xml: 'application/xml',
    zip: 'application/zip',
  },
} as const;
