export const description = 'Composable reactive streams with a full operator library and ecosystem adapters.';

export const loader = () => import('@vielzeug/flux');

export const apiExports = [
  'flux',
  'createSubject',
  'createBehaviorSubject',
  'of',
  'from',
  'fromEvent',
  'interval',
  'timer',
  'empty',
  'never',
  'throwError',
  'map',
  'filter',
  'scan',
  'switchMap',
  'flatMap',
  'concatMap',
  'distinctUntilChanged',
  'startWith',
  'bufferCount',
  'pairwise',
  'take',
  'skip',
  'first',
  'last',
  'takeWhile',
  'takeUntil',
  'debounce',
  'throttle',
  'sample',
  'merge',
  'concat',
  'combineLatest',
  'withLatestFrom',
  'race',
  'zip',
  'forkJoin',
  'share',
  'shareReplay',
  'tap',
  'delay',
  'timeout',
  'catchError',
  'retry',
  'finalize',
  'toPromise',
  'toArray',
  'fromSignal',
  'toSignal',
  'fromBus',
  'toBus',
  'fromPulse',
  'fromPresence',
  'fromSse',
  'fromReadable',
  'fromQuery',
  'FluxError',
  'FluxDisposedError',
  'FluxTimeoutError',
  'FluxBufferOverflowError',
] as const;
