export const description = 'Timezone-aware date/time library built on Temporal.';

export const loader = () => import('@vielzeug/tempo');

export const apiExports = [
  'clamp',
  'classify',
  'dateRange',
  'difference',
  'endOf',
  'expires',
  'format',
  'formatDuration',
  'formatInstant',
  'formatParts',
  'formatRange',
  'formatRangeParts',
  'formatRelative',
  'formatZoned',
  'humanize',
  'isAfter',
  'isBefore',
  'isSame',
  'isValid',
  'now',
  'nowInstant',
  'parseDate',
  'parseDuration',
  'parseInstant',
  'parsePlainDate',
  'parsePlainDateTime',
  'parseZoned',
  'recurrence',
  'shift',
  'startOf',
  'timeDiff',
  'toInstant',
  'toZoned',
  'within',
] as const;
