import type { Expansion } from '../domain/types';

export const expansions: Expansion[] = [
  {
    artwork: null,
    description: 'The base game: four hunters, twelve monsters and the eleven-chapter campaign.',
    family: 'core',
    id: 'core',
    name: 'Core Box',
    purchaseUrl: null,
    required: true,
  },
  {
    artwork: '/game_boxes/box_nightmare_expansion.webp',
    description: 'Zekath, Zekalith, Xitheros and Taraska. Adds five campaign quests in the storm-torn north.',
    family: 'monsters',
    id: 'nightmare',
    name: 'Nightmare Expansion',
    purchaseUrl: 'https://reggiegames.com/products/nightmare-expansion',
    required: false,
  },
  {
    artwork: '/game_boxes/box_feather_expansion.webp',
    description: 'Pazis and Nagarjas. Adds the Feather Forge card and five quests in the jungle of Muara.',
    family: 'monsters',
    id: 'feather',
    name: 'Feather Expansion',
    purchaseUrl: 'https://reggiegames.com/products/feather-expansion',
    required: false,
  },
  {
    artwork: '/game_boxes/box_venon_expansion.webp',
    description: 'Hydar and Reikal. Adds the Venom Forge card and five quests in the dark swamps.',
    family: 'monsters',
    id: 'venom',
    name: 'Venom Expansion',
    purchaseUrl: 'https://reggiegames.com/products/venom-expansion',
    required: false,
  },
  {
    artwork: '/game_boxes/box_ice_expansion.webp',
    description: 'Sirkaaj and Mamuraak. Adds the Ice Forge card and four quests across the frozen wastes.',
    family: 'monsters',
    id: 'ice',
    name: 'Ice Expansion',
    purchaseUrl: 'https://reggiegames.com/products/ice-expansion',
    required: false,
  },
  {
    artwork: '/game_boxes/box_head_of_the_wild_expansion.webp',
    description: 'Zaraya and Drusk, with the Spear and War Drum weapon classes.',
    family: 'hunters',
    id: 'heart-of-the-wild',
    name: 'Heart of The Wild',
    purchaseUrl: 'https://reggiegames.com/products/heart-of-the-wild',
    required: false,
  },
  {
    artwork: '/game_boxes/box_mount_havoc_expansion.webp',
    description: 'Heleren and Karah, with the Gunbow and Dual Blades weapon classes.',
    family: 'hunters',
    id: 'mount-havoc',
    name: 'Mount Havoc',
    purchaseUrl: 'https://reggiegames.com/products/5th-expansion',
    required: false,
  },
  {
    artwork: '/game_boxes/box_nightmare_expasion_2.webp',
    description: 'Nightmare variants for additional monsters with new reaction mechanics.',
    family: 'monsters',
    id: 'nightmare-2',
    name: 'Nightmare 2 Expansion',
    purchaseUrl: 'https://reggiegames.com/products/nightmare-2',
    required: false,
  },
  {
    artwork: '/game_boxes/box_biome_swamp_nightmare.webp',
    description: 'Nightmare and Endless Swamp biomes with toxic fume and transformation mechanics.',
    family: 'biomes',
    id: 'biome-endless-swamp-nightmare',
    name: 'Biome Expansion: Endless Swamp & Nightmare',
    purchaseUrl: 'https://reggiegames.com/products/biome-expansion-endless-swamp-and-nightmare',
    required: false,
  },
  {
    artwork: '/game_boxes/box_bioma_metal_thunder.webp',
    description: 'Goldarks and Thunder Mountains biomes.',
    family: 'biomes',
    id: 'biome-goldarks-thunder-mountains',
    name: 'Biome Expansion: Goldarks & Thunder Mountains',
    purchaseUrl: 'https://reggiegames.com/products/biome-expansion-goldarks-and-thunder-mountains',
    required: false,
  },
  {
    artwork: '/game_boxes/box_bioma_desert_feather.webp',
    description: 'Niz-Maraga and Sunset Plains biomes.',
    family: 'biomes',
    id: 'biome-niz-maraga-sunset-plains',
    name: 'Biome Expansion: Niz-Maraga & Sunset Plains',
    purchaseUrl: 'https://reggiegames.com/products/biome-expansion-niz-maraga-and-sunset-plains',
    required: false,
  },
  {
    artwork: '/game_boxes/box_bioma_ice_fire.webp',
    description: 'Woltyar and Frozen Wastes biomes.',
    family: 'biomes',
    id: 'biome-woltyar-frozen-wastes',
    name: 'Biome Expansion: Woltyar & Frozen Wastes',
    purchaseUrl: 'https://reggiegames.com/products/biome-expansion-woltyar-and-frozen-wastes',
    required: false,
  },
  {
    artwork: '/game_boxes/box_bioma_coral-crystal.webp',
    description: 'Crystal Caves and Flooded Wilds biomes with crystal tokens and deep-water terrain.',
    family: 'biomes',
    id: 'biome-crystal-caves-flooded-wilds',
    name: 'Biome Expansion: Crystal Caves & Flooded Wilds',
    purchaseUrl: 'https://reggiegames.com/products/biome-expansion-crystal-caves-and-flooded-wilds',
    required: false,
  },
];

export const expansionById = (id: string): Expansion | undefined => expansions.find((entry) => entry.id === id);
