/**
 * Every Lucide icon the app renders, registered up front so any template name
 * resolves. `icons.test.ts` scans the source tree and fails when a template
 * uses a name that is missing here, so the set cannot drift silently.
 */

import { registerIcons } from '@vielzeug/refine/icon';
import {
  AlertTriangle,
  ArrowLeft,
  ArrowRightLeft,
  ArrowUpCircle,
  Backpack,
  BookmarkPlus,
  BookOpen,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDashed,
  CircleDot,
  CircleHelp,
  Clock,
  Compass,
  Copy,
  Crosshair,
  Database,
  Dices,
  Download,
  Eraser,
  ExternalLink,
  EyeOff,
  FastForward,
  Flame,
  Globe,
  Hammer,
  Headphones,
  Heart,
  HeartCrack,
  HelpCircle,
  Image,
  Info,
  Keyboard,
  Languages,
  Layers,
  LayoutGrid,
  LayoutPanelLeft,
  Library,
  Lock,
  LogOut,
  Map,
  Maximize,
  Maximize2,
  Medal,
  Minimize,
  Minus,
  Monitor,
  Moon,
  Mountain,
  Package,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Pencil,
  Play,
  Plus,
  Repeat,
  Repeat1,
  RotateCcw,
  Save,
  Scroll,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShieldOff,
  ShoppingCart,
  SkipBack,
  SkipForward,
  Skull,
  Snowflake,
  Sparkles,
  Square,
  Sun,
  Swords,
  Timer,
  Trash2,
  TriangleAlert,
  Trophy,
  User,
  Users,
  Volume2,
  VolumeX,
  Wand2,
  Waypoints,
  Weight,
  Wifi,
  Wind,
  X,
  Zap,
  ZapOff,
} from 'lucide';

const APP_ICONS = {
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right-left': ArrowRightLeft,
  'arrow-up-circle': ArrowUpCircle,
  backpack: Backpack,
  'book-open': BookOpen,
  'bookmark-plus': BookmarkPlus,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-dashed': CircleDashed,
  'circle-dot': CircleDot,
  'circle-help': CircleHelp,
  clock: Clock,
  compass: Compass,
  copy: Copy,
  crosshair: Crosshair,
  database: Database,
  dices: Dices,
  download: Download,
  eraser: Eraser,
  'external-link': ExternalLink,
  'eye-off': EyeOff,
  'fast-forward': FastForward,
  flame: Flame,
  globe: Globe,
  hammer: Hammer,
  headphones: Headphones,
  heart: Heart,
  'heart-crack': HeartCrack,
  'help-circle': HelpCircle,
  image: Image,
  info: Info,
  keyboard: Keyboard,
  languages: Languages,
  layers: Layers,
  'layout-grid': LayoutGrid,
  'layout-panel-left': LayoutPanelLeft,
  library: Library,
  lock: Lock,
  'log-out': LogOut,
  map: Map,
  maximize: Maximize,
  'maximize-2': Maximize2,
  medal: Medal,
  minimize: Minimize,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  package: Package,
  palette: Palette,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  repeat: Repeat,
  'repeat-1': Repeat1,
  'rotate-ccw': RotateCcw,
  save: Save,
  scroll: Scroll,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-off': ShieldOff,
  'shopping-cart': ShoppingCart,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  skull: Skull,
  snowflake: Snowflake,
  sparkles: Sparkles,
  square: Square,
  sun: Sun,
  swords: Swords,
  timer: Timer,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  user: User,
  users: Users,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'wand-2': Wand2,
  waypoints: Waypoints,
  weight: Weight,
  wifi: Wifi,
  wind: Wind,
  x: X,
  zap: Zap,
  'zap-off': ZapOff,
};

/** The registered names: the coverage test diffs template usage against this. */
export const APP_ICON_NAMES = Object.keys(APP_ICONS);

registerIcons(APP_ICONS);
