/**
 * The icons refine's own components render — chevrons, close marks, spinners,
 * the icons inputs and overlays label themselves with. Imported by `icon.ts`
 * so they resolve wherever `ore-icon` is used. Apps needing more than this set
 * register their own via `registerIcons()` or import `@vielzeug/refine/icon-lucide`
 * for the complete Lucide library.
 */
import {
  AlertCircle,
  ArrowRight,
  ArrowUpDown,
  Calendar,
  Camera,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  Clock,
  Columns2,
  Copy,
  Eye,
  EyeOff,
  File,
  Filter,
  Gauge,
  Loader2,
  Mail,
  Menu,
  Minus,
  Package,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Square,
  Star,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  X,
  Zap,
} from 'lucide';
import { registerIcons } from './icon-registry';

registerIcons({
  AlertCircle: AlertCircle,
  ArrowRight: ArrowRight,
  ArrowUpDown: ArrowUpDown,
  Calendar: Calendar,
  Camera: Camera,
  ChartLine: ChartLine,
  Check: Check,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronsLeft: ChevronsLeft,
  ChevronsRight: ChevronsRight,
  CircleAlert: CircleAlert,
  Clock: Clock,
  Columns2: Columns2,
  Copy: Copy,
  Eye: Eye,
  EyeOff: EyeOff,
  File: File,
  Filter: Filter,
  Gauge: Gauge,
  Loader2: Loader2,
  Mail: Mail,
  Menu: Menu,
  Minus: Minus,
  Package: Package,
  Pause: Pause,
  Play: Play,
  Plus: Plus,
  RefreshCw: RefreshCw,
  Save: Save,
  Search: Search,
  Square: Square,
  Star: Star,
  Trash2: Trash2,
  TriangleAlert: TriangleAlert,
  Upload: Upload,
  User: User,
  X: X,
  Zap: Zap,
});
