import browserslist from 'browserslist';
import { browserslistToTargets } from 'lightningcss';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig, type DefaultTheme, type UserConfig } from 'vitepress';

import type { ThemeConfig } from './theme/types';

import { getPackagesData } from './theme/utils/packageData';

const __dirname = dirname(fileURLToPath(import.meta.url));

const NON_COLLAPSIBLE_PACKAGE_PATHS = new Set(['/buildit/']);

const isPackageSidebarPath = (path: string): boolean => /^\/[a-z]+it\/$/.test(path);

const makePackageSidebarsCollapsible = (sidebar: DefaultTheme.SidebarMulti): DefaultTheme.SidebarMulti => {
  return Object.fromEntries(
    Object.entries(sidebar).map(([path, items]) => {
      if (!isPackageSidebarPath(path) || NON_COLLAPSIBLE_PACKAGE_PATHS.has(path)) {
        return [path, items];
      }

      const normalizedItems = items.map((item) => {
        if (!('items' in item)) return item;

        return {
          ...item,
          collapsed: item.collapsed ?? item.text === 'API Reference',
        };
      });

      return [path, normalizedItems];
    }),
  ) as DefaultTheme.SidebarMulti;
};

export default defineConfig({
  base: '/',
  description: 'Documentation for the Vielzeug monorepo',
  head: [
    // Favicons
    ['link', { href: '/favicon/favicon.svg', rel: 'icon', type: 'image/svg+xml' }],
    ['link', { href: '/favicon/favicon-96x96.png', rel: 'icon', sizes: '96x96', type: 'image/png' }],
    ['link', { href: '/favicon/favicon.ico', rel: 'icon', type: 'image/x-icon' }],
    ['link', { href: '/favicon/apple-touch-icon.png', rel: 'apple-touch-icon', sizes: '180x180' }],
    ['link', { href: '/favicon/site.webmanifest', rel: 'manifest' }],
    [
      'link',
      {
        href: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200',
        rel: 'stylesheet',
      },
    ],
    // Theme and mobile app configuration
    ['meta', { content: '#f6ac2c', name: 'theme-color' }],
    ['meta', { content: 'yes', name: 'mobile-web-app-capable' }],
    ['meta', { content: 'black', name: 'mobile-web-app-status-bar-style' }],
  ],
  ignoreDeadLinks: true,
  sitemap: {
    hostname: 'https://vielzeug.dev',
    transformItems: (items) => {
      return items.map((item) => {
        return {
          ...item,
          url: `vielzeug/${item.url}`, // Fix sitemap URLs
        };
      });
    },
  },
  themeConfig: {
    logo: '/logo-main.svg',
    nav: [
      { link: '/guide/', text: 'Guide' },
      {
        items: [
          {
            items: [
              { link: '/logit/', text: 'Logit' },
              { link: '/timit/', text: 'Timit' },
              { link: '/toolkit/', text: 'Toolkit' },
            ],
            text: 'Core & Utilities',
          },
          {
            items: [
              { link: '/deposit/', text: 'Deposit' },
              { link: '/eventit/', text: 'Eventit' },
              { link: '/fetchit/', text: 'Fetchit' },
              { link: '/stateit/', text: 'Stateit' },
            ],
            text: 'Data & State',
          },
          {
            items: [
              { link: '/craftit/', text: 'Craftit' },
              { link: '/dragit/', text: 'Dragit' },
              { link: '/floatit/', text: 'Floatit' },
              { link: '/formit/', text: 'Formit' },
              { link: '/i18nit/', text: 'i18nit' },
              { link: '/validit/', text: 'Validit' },
              { link: '/virtualit/', text: 'Virtualit' },
            ],
            text: 'Frontend & Logic',
          },
          {
            items: [
              { link: '/permit/', text: 'Permit' },
              { link: '/routeit/', text: 'Routeit' },
              { link: '/wireit/', text: 'Wireit' },
              { link: '/workit/', text: 'Workit' },
            ],
            text: 'Architecture & Security',
          },
        ],
        text: 'Packages',
      },
      { link: '/buildit/', text: 'Components' },
      { link: '/repl', text: 'REPL' },
    ],
    packages: getPackagesData(),
    search: {
      provider: 'local',
    },
    sidebar: makePackageSidebarsCollapsible({
      '/buildit/': [
        { link: '/buildit/', text: 'Overview' },
        {
          items: [
            {
              collapsed: true,
              items: [
                { link: '/buildit/usage#basic-usage', text: 'Basic Usage' },
                { link: '/buildit/usage#slots', text: 'Slots' },
                { link: '/buildit/usage#accessibility', text: 'Accessibility' },
              ],
              link: '/buildit/usage',
              text: 'Usage Guide',
            },
            {
              collapsed: true,
              items: [
                { link: '/buildit/frameworks#react', text: 'React' },
                { link: '/buildit/frameworks#vue-3', text: 'Vue 3' },
                { link: '/buildit/frameworks#svelte', text: 'Svelte' },
                { link: '/buildit/frameworks#angular', text: 'Angular' },
                { link: '/buildit/frameworks#ssr-considerations', text: 'SSR' },
              ],
              link: '/buildit/frameworks',
              text: 'Framework Integration',
            },
            {
              collapsed: true,
              items: [
                { link: '/buildit/theming#design-tokens', text: 'Design Tokens' },
                { link: '/buildit/theming#dark-mode', text: 'Dark Mode' },
                { link: '/buildit/theming#global-customization', text: 'Global Customization' },
                { link: '/buildit/theming#component-customization', text: 'Component Customization' },
              ],
              link: '/buildit/theming',
              text: 'Theming',
            },
          ],
          text: 'Getting Started',
        },
        {
          items: [
            {
              collapsed: true,
              items: [
                { link: '/buildit/components/accordion', text: 'Accordion' },
                { link: '/buildit/components/tabs', text: 'Tabs' },
              ],
              text: 'Disclosure',
            },
            {
              collapsed: true,
              items: [
                { link: '/buildit/components/alert', text: 'Alert' },
                { link: '/buildit/components/badge', text: 'Badge' },
                { link: '/buildit/components/chip', text: 'Chip' },
                { link: '/buildit/components/progress', text: 'Progress' },
                { link: '/buildit/components/skeleton', text: 'Skeleton' },
                { link: '/buildit/components/toast', text: 'Toast' },
              ],
              text: 'Feedback',
            },
            {
              collapsed: true,
              items: [{ link: '/buildit/components/button', text: 'Button' }],
              text: 'Actions',
            },
            {
              collapsed: true,
              items: [
                { link: '/buildit/components/avatar', text: 'Avatar' },
                { link: '/buildit/components/breadcrumb', text: 'Breadcrumb' },
                { link: '/buildit/components/card', text: 'Card' },
                { link: '/buildit/components/pagination', text: 'Pagination' },
                { link: '/buildit/components/separator', text: 'Separator' },
                { link: '/buildit/components/table', text: 'Table' },
                { link: '/buildit/components/text', text: 'Text' },
              ],
              text: 'Content',
            },
            {
              collapsed: true,
              items: [
                { link: '/buildit/components/dialog', text: 'Dialog' },
                { link: '/buildit/components/drawer', text: 'Drawer' },
                { link: '/buildit/components/menu', text: 'Menu' },
                { link: '/buildit/components/popover', text: 'Popover' },
                { link: '/buildit/components/tooltip', text: 'Tooltip' },
              ],
              text: 'Overlay',
            },
            {
              collapsed: true,
              items: [
                { link: '/buildit/components/checkbox', text: 'Checkbox' },
                { link: '/buildit/components/combobox', text: 'Combobox' },
                { link: '/buildit/components/file-input', text: 'File Input' },
                { link: '/buildit/components/form', text: 'Form' },
                { link: '/buildit/components/input', text: 'Input' },
                { link: '/buildit/components/number-input', text: 'Number Input' },
                { link: '/buildit/components/otp-input', text: 'OTP Input' },
                { link: '/buildit/components/radio', text: 'Radio' },
                { link: '/buildit/components/rating', text: 'Rating' },
                { link: '/buildit/components/select', text: 'Select' },
                { link: '/buildit/components/slider', text: 'Slider' },
                { link: '/buildit/components/switch', text: 'Switch' },
                { link: '/buildit/components/textarea', text: 'Textarea' },
              ],
              text: 'Form',
            },
            {
              collapsed: true,
              items: [
                { link: '/buildit/components/box', text: 'Box' },
                { link: '/buildit/components/grid', text: 'Grid' },
                { link: '/buildit/components/sidebar', text: 'Sidebar' },
              ],
              text: 'Layout',
            },
          ],
          text: 'Components',
        },
        {
          items: [
            { link: '/buildit/api', text: 'API Reference' },
            {
              items: [
                { link: '/buildit/examples/common-patterns', text: 'Common Patterns' },
                { link: '/buildit/examples/guideline-oriented-recipes', text: 'Guideline-Oriented Recipes' },
                { link: '/buildit/examples/settings-panel-with-switches', text: 'Settings Panel with Switches' },
              ],
              link: '/buildit/examples',
              text: 'Examples',
            },
          ],
          text: 'Reference',
        },
      ],
      '/craftit/': [
        { link: '/craftit/', text: 'Overview' },
        {
          collapsed: false,
          items: [
            { link: '/craftit/usage#define', text: 'define()' },
            { link: '/craftit/usage#signals-and-state', text: 'Signals' },
            { link: '/craftit/usage#template-bindings', text: 'Templates' },
            { link: '/craftit/usage#directives-subpath', text: 'Directives' },
            { link: '/craftit/usage#lifecycle-and-runtime-helpers', text: 'Lifecycle' },
            { link: '/craftit/usage#props-and-attributes', text: 'Props' },
            { link: '/craftit/usage#slots-and-emits', text: 'Slots & Emits' },
            { link: '/craftit/usage#context-provide--inject', text: 'Context / DI' },
            { link: '/craftit/usage#form-associated-elements', text: 'Forms' },
            { link: '/craftit/usage#platform-observers', text: 'Observers' },
            { link: '/craftit/usage#testing-utilities', text: 'Testing' },
          ],
          link: '/craftit/usage',
          text: 'Usage Guide',
        },
        {
          collapsed: true,
          items: [
            { link: '/craftit/api#entry-points', text: 'Entry Points' },
            { link: '/craftit/api#core-component-api', text: 'Core API' },
            { link: '/craftit/api#runtime-helpers', text: 'Runtime' },
            { link: '/craftit/api#props-api', text: 'Props' },
            { link: '/craftit/api#slots-and-emits', text: 'Slots & Emits' },
            { link: '/craftit/api#context-api', text: 'Context' },
            { link: '/craftit/api#form-associated-api', text: 'Forms' },
            { link: '/craftit/api#observer-apis', text: 'Observers' },
            { link: '/craftit/api#directive-apis', text: 'Directives' },
            { link: '/craftit/api#testing-apis', text: 'Testing' },
            { link: '/craftit/api#stateit-re-exports', text: 'Stateit Re-exports' },
          ],
          link: '/craftit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/craftit/examples/context-provider-and-consumer', text: 'Context Provider and Consumer' },
            { link: '/craftit/examples/counter-component', text: 'Counter Component' },
            { link: '/craftit/examples/form-associated-rating-input', text: 'Form-Associated Rating Input' },
            { link: '/craftit/examples/observers-in-onmount', text: 'Observers in `onMount`' },
            { link: '/craftit/examples/search-list-with-directives', text: 'Search List with Directives' },
            {
              link: '/craftit/examples/test-example-at-vielzeug-craftit-test',
              text: 'Test Example (`@vielzeug/craftit/test`)',
            },
            { link: '/craftit/examples/typed-props-and-emits', text: 'Typed Props and Emits' },
          ],
          link: '/craftit/examples',
          text: 'Examples',
        },
      ],
      '/deposit/': [
        { link: '/deposit/', text: 'Overview' },
        {
          items: [
            { link: '/deposit/usage#defining-a-schema', text: 'Defining a Schema' },
            { link: '/deposit/usage#inline-schema', text: 'Inline Schema' },
            { link: '/deposit/usage#creating-an-adapter', text: 'Creating an Adapter' },
            { link: '/deposit/usage#crud-operations', text: 'CRUD Operations' },
            { link: '/deposit/usage#query-builder', text: 'Query Builder' },
            { link: '/deposit/usage#ttl', text: 'TTL' },
            { link: '/deposit/usage#transactions', text: 'Transactions' },
            { link: '/deposit/usage#schema-migrations', text: 'Schema Migrations' },
          ],
          link: '/deposit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/deposit/api#package-entry-points', text: 'Package Entry Points' },
            { link: '/deposit/api#factory-functions', text: 'Factory Functions' },
            { link: '/deposit/api#adapter-interface', text: 'Adapter Interface' },
            { link: '/deposit/api#indexeddbhandle', text: 'IndexedDBHandle' },
            { link: '/deposit/api#querybuilder', text: 'QueryBuilder' },
            { link: '/deposit/api#types', text: 'Types' },
          ],
          link: '/deposit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/deposit/examples/basic-examples', text: 'Basic Examples' },
            { link: '/deposit/examples/advanced-examples', text: 'Advanced Examples' },
          ],
          link: '/deposit/examples',
          text: 'Examples',
        },
      ],
      '/dragit/': [
        { link: '/dragit/', text: 'Overview' },
        {
          items: [
            { link: '/dragit/usage#drop-zone', text: 'Drop Zone' },
            { link: '/dragit/usage#accept-filtering', text: 'Accept Filtering' },
            { link: '/dragit/usage#hover-state', text: 'Hover State' },
            { link: '/dragit/usage#dropeffect', text: 'dropEffect' },
            { link: '/dragit/usage#disabled-state', text: 'Disabled State' },
            { link: '/dragit/usage#sortable', text: 'Sortable' },
            { link: '/dragit/usage#drag-handles', text: 'Drag Handles' },
            { link: '/dragit/usage#dynamic-lists', text: 'Dynamic Lists' },
            { link: '/dragit/usage#styling-the-placeholder', text: 'Styling' },
            { link: '/dragit/usage#cleanup', text: 'Cleanup' },
          ],
          link: '/dragit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/dragit/api#types', text: 'Types' },
            { link: '/dragit/api#createdropzone', text: 'createDropZone()' },
            { link: '/dragit/api#dropzone-interface', text: 'DropZone Interface' },
            { link: '/dragit/api#createsortable', text: 'createSortable()' },
            { link: '/dragit/api#sortable-interface', text: 'Sortable Interface' },
            { link: '/dragit/api#dom-attributes', text: 'DOM Attributes' },
          ],
          link: '/dragit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/dragit/examples/framework-integration', text: 'Framework Integration' },
            {
              link: '/dragit/examples/combined-sortable-with-inline-editing',
              text: 'Combined: sortable with inline editing',
            },
            { link: '/dragit/examples/file-upload-drop-zone', text: 'File upload drop zone' },
            { link: '/dragit/examples/sortable-list', text: 'Sortable list' },
            { link: '/dragit/examples/using-using-for-scoped-cleanup', text: 'Using `using` for scoped cleanup' },
            { link: '/dragit/examples/web-component-with-craftit', text: 'Web Component with craftit' },
          ],
          link: '/dragit/examples',
          text: 'Examples',
        },
      ],
      '/eventit/': [
        { link: '/eventit/', text: 'Overview' },
        {
          items: [
            { link: '/eventit/usage#event-maps', text: 'Event Maps' },
            { link: '/eventit/usage#subscribing', text: 'Subscribing' },
            { link: '/eventit/usage#emitting-events', text: 'Emitting Events' },
            { link: '/eventit/usage#awaiting-events', text: 'Awaiting Events' },
            { link: '/eventit/usage#async-iteration', text: 'Async Iteration' },
            { link: '/eventit/usage#error-handling', text: 'Error Handling' },
            { link: '/eventit/usage#dispose--cleanup', text: 'Dispose & Cleanup' },
            { link: '/eventit/usage#testing', text: 'Testing' },
          ],
          link: '/eventit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/eventit/api#package-entry-points', text: 'Package Entry Points' },
            { link: '/eventit/api#types', text: 'Types' },
            { link: '/eventit/api#busdisposederror', text: 'BusDisposedError' },
            { link: '/eventit/api#createbus', text: 'createBus()' },
            { link: '/eventit/api#bus-interface', text: 'Bus Interface' },
            { link: '/eventit/api#buslistenercount', text: 'listenerCount()' },
            { link: '/eventit/api#testing-utilities', text: 'Testing Utilities' },
            { link: '/eventit/api#createtestbus', text: 'createTestBus()' },
          ],
          link: '/eventit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/eventit/examples/framework-integration', text: 'Framework Integration' },
            { link: '/eventit/examples/awaiting-a-one-time-event', text: 'Awaiting a one-time event' },
            { link: '/eventit/examples/custom-error-boundary', text: 'Custom error boundary' },
            { link: '/eventit/examples/handling-disposal-in-async-code', text: 'Handling disposal in async code' },
            { link: '/eventit/examples/inspecting-listener-counts', text: 'Inspecting listener counts' },
            { link: '/eventit/examples/module-level-bus', text: 'Module-level bus' },
            { link: '/eventit/examples/request-scoping', text: 'Request scoping' },
            { link: '/eventit/examples/standalone-entry', text: 'Standalone entry' },
            { link: '/eventit/examples/streaming-with-events', text: 'Streaming with `events()`' },
            { link: '/eventit/examples/testing-with-createtestbus', text: 'Testing with `createTestBus`' },
          ],
          link: '/eventit/examples',
          text: 'Examples',
        },
      ],
      '/fetchit/': [
        { link: '/fetchit/', text: 'Overview' },
        {
          items: [
            { link: '/fetchit/usage#http-client', text: 'HTTP Client' },
            { link: '/fetchit/usage#interceptors', text: 'Interceptors' },
            { link: '/fetchit/usage#query-client', text: 'Query Client' },
            { link: '/fetchit/usage#query-callbacks', text: 'Query Callbacks' },
            { link: '/fetchit/usage#standalone-mutation', text: 'Standalone Mutation' },
            { link: '/fetchit/usage#error-handling', text: 'Error Handling' },
          ],
          link: '/fetchit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/fetchit/api#createapi', text: 'createApi()' },
            { link: '/fetchit/api#createquery', text: 'createQuery()' },
            { link: '/fetchit/api#createmutation', text: 'createMutation()' },
            { link: '/fetchit/api#httperror', text: 'HttpError' },
            { link: '/fetchit/api#types', text: 'Types' },
          ],
          link: '/fetchit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/fetchit/examples/framework-integration', text: 'Framework Integration' },
            { link: '/fetchit/examples/authentication', text: 'Authentication' },
            { link: '/fetchit/examples/crud-operations', text: 'CRUD Operations' },
            { link: '/fetchit/examples/disposal', text: 'Disposal' },
            { link: '/fetchit/examples/error-handling-patterns', text: 'Error Handling Patterns' },
            { link: '/fetchit/examples/file-uploads', text: 'File Uploads' },
            { link: '/fetchit/examples/mutation-cancel', text: 'Mutation Cancel' },
            { link: '/fetchit/examples/optimistic-updates', text: 'Optimistic Updates' },
            { link: '/fetchit/examples/polling', text: 'Polling' },
            { link: '/fetchit/examples/query-callbacks', text: 'Query Callbacks' },
          ],
          link: '/fetchit/examples',
          text: 'Examples',
        },
      ],
      '/floatit/': [
        { link: '/floatit/', text: 'Overview' },
        {
          items: [
            { link: '/floatit/usage#placement', text: 'Placement' },
            { link: '/floatit/usage#positionfloat', text: 'positionFloat' },
            { link: '/floatit/usage#computeposition', text: 'computePosition' },
            { link: '/floatit/usage#middleware', text: 'Middleware' },
            { link: '/floatit/usage#autoupdate', text: 'autoUpdate' },
            { link: '/floatit/usage#common-patterns', text: 'Common Patterns' },
          ],
          link: '/floatit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/floatit/api#core-functions', text: 'Core Functions' },
            { link: '/floatit/api#middlewares', text: 'Middlewares' },
            { link: '/floatit/api#types', text: 'Types' },
          ],
          link: '/floatit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/floatit/examples/context-menu', text: 'Context Menu' },
            { link: '/floatit/examples/custom-middleware', text: 'Custom Middleware' },
            { link: '/floatit/examples/dropdown-select', text: 'Dropdown / Select' },
            { link: '/floatit/examples/popover-with-arrow', text: 'Popover with Arrow' },
            { link: '/floatit/examples/tooltip', text: 'Tooltip' },
            { link: '/floatit/examples/with-craftit-component', text: 'With Craftit Component' },
          ],
          link: '/floatit/examples',
          text: 'Examples',
        },
      ],
      '/formit/': [
        { link: '/formit/', text: 'Overview' },
        {
          items: [
            { link: '/formit/usage#basic-usage', text: 'Basic Usage' },
            { link: '/formit/usage#validation', text: 'Validation' },
            { link: '/formit/usage#submission', text: 'Submission' },
            { link: '/formit/usage#subscriptions', text: 'Subscriptions' },
            { link: '/formit/usage#bind', text: 'Bind' },
            { link: '/formit/usage#reset', text: 'Reset' },
            { link: '/formit/usage#dirty-and-touched-state', text: 'Dirty & Touched' },
            { link: '/formit/usage#arrays-and-multi-select', text: 'Array Fields' },
            { link: '/formit/usage#file-uploads', text: 'File Uploads' },
            { link: '/formit/usage#advanced-patterns', text: 'Advanced Patterns' },
            { link: '/formit/usage#best-practices', text: 'Best Practices' },
          ],
          link: '/formit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/formit/api#createform-init', text: 'createForm()' },
            { link: '/formit/api#values', text: 'Values' },
            { link: '/formit/api#field-state', text: 'Field State' },
            { link: '/formit/api#touch', text: 'Touch' },
            { link: '/formit/api#array-fields', text: 'Array Fields' },
            { link: '/formit/api#validation', text: 'Validation' },
            { link: '/formit/api#submit', text: 'Submit' },
            { link: '/formit/api#subscriptions', text: 'Subscriptions' },
            { link: '/formit/api#standalone-utilities', text: 'Standalone Utilities' },
            { link: '/formit/api#error-classes', text: 'Error Classes' },
            { link: '/formit/api#exported-types', text: 'Types' },
          ],
          link: '/formit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/formit/examples/framework-integration', text: 'Framework Integration' },
            { link: '/formit/examples/best-practices', text: 'Best Practices' },
            { link: '/formit/examples/contact-form-with-file-upload', text: 'Contact Form with File Upload' },
            { link: '/formit/examples/dynamic-form-fields', text: 'Dynamic Form Fields' },
            { link: '/formit/examples/form-with-conditional-fields', text: 'Form with Conditional Fields' },
            { link: '/formit/examples/login-form', text: 'Login Form' },
            { link: '/formit/examples/multi-step-wizard', text: 'Multi-Step Wizard' },
            { link: '/formit/examples/registration-form', text: 'Registration Form' },
            { link: '/formit/examples/search-form-with-debounce', text: 'Search Form with Debounce' },
            { link: '/formit/examples/see-also', text: 'See Also' },
          ],
          link: '/formit/examples',
          text: 'Examples',
        },
      ],
      '/guide/': [
        { link: '/guide/', text: 'Getting Started' },
        {
          items: [
            { link: '/guide/docs-style-guide', text: 'Documentation Style Guide' },
            { link: '/guide/building-a-typed-form-flow', text: 'Building a Typed Form Flow' },
            { link: '/guide/state-and-routing', text: 'State and Routing' },
          ],
          text: 'Guides',
        },
      ],
      '/i18nit/': [
        { link: '/i18nit/', text: 'Overview' },
        {
          items: [
            { link: '/i18nit/usage#basic-usage', text: 'Basic Usage' },
            { link: '/i18nit/usage#variable-interpolation', text: 'Interpolation' },
            { link: '/i18nit/usage#pluralisation', text: 'Pluralisation' },
            { link: '/i18nit/usage#async-loading', text: 'Async Loading' },
            { link: '/i18nit/usage#scoping', text: 'Scope & withLocale' },
            { link: '/i18nit/usage#formatting-helpers', text: 'Formatting' },
            { link: '/i18nit/usage#subscriptions', text: 'Subscriptions' },
          ],
          link: '/i18nit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/i18nit/api#types', text: 'Types' },
            { link: '/i18nit/api#createi18n', text: 'createI18n()' },
            { link: '/i18nit/api#i18n-instance', text: 'I18n Instance' },
            { link: '/i18nit/api#boundi18n', text: 'BoundI18n' },
          ],
          link: '/i18nit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/i18nit/examples/framework-integration', text: 'Framework Integration' },
            { link: '/i18nit/examples/async-loading-and-reload', text: 'Async Loading and Reload' },
            { link: '/i18nit/examples/batched-catalog-updates', text: 'Batched Catalog Updates' },
            { link: '/i18nit/examples/diagnostics-hook', text: 'Diagnostics Hook' },
            { link: '/i18nit/examples/locale-bound-translator', text: 'Locale-bound Translator' },
            { link: '/i18nit/examples/locale-switcher', text: 'Locale Switcher' },
            { link: '/i18nit/examples/scoped-translator', text: 'Scoped Translator' },
            { link: '/i18nit/examples/shared-instance-setup', text: 'Shared Instance Setup' },
            { link: '/i18nit/examples/ssr-rendering-with-withlocale', text: 'SSR Rendering with withLocale' },
          ],
          link: '/i18nit/examples',
          text: 'Examples',
        },
      ],
      '/logit/': [
        { link: '/logit/', text: 'Overview' },
        {
          items: [
            { link: '/logit/usage#logger-instances', text: 'Logger Instances' },
            { link: '/logit/usage#configuration', text: 'Configuration' },
            { link: '/logit/usage#logging-methods', text: 'Logging Methods' },
            { link: '/logit/usage#scoped-loggers', text: 'Scoped Loggers' },
            { link: '/logit/usage#child-loggers', text: 'Child Loggers' },
            { link: '/logit/usage#remote-logging', text: 'Remote Logging' },
            { link: '/logit/usage#best-practices', text: 'Best Practices' },
            { link: '/logit/usage#testing', text: 'Testing' },
          ],
          link: '/logit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/logit/api#createloggerinitial', text: 'createLogger()' },
            { link: '/logit/api#logit-object', text: 'Logit Object' },
            { link: '/logit/api#types', text: 'Types' },
          ],
          link: '/logit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/logit/examples/child-logger-overrides', text: 'Child Logger Overrides' },
            { link: '/logit/examples/module-logger-pattern', text: 'Module Logger Pattern' },
            { link: '/logit/examples/production-setup', text: 'Production Setup' },
            { link: '/logit/examples/react-integration', text: 'React Integration' },
            { link: '/logit/examples/request-middleware', text: 'Request Middleware' },
            { link: '/logit/examples/testing', text: 'Testing' },
            { link: '/logit/examples/timing-and-grouping', text: 'Timing and Grouping' },
          ],
          link: '/logit/examples',
          text: 'Examples',
        },
      ],
      '/permit/': [
        { link: '/permit/', text: 'Overview' },
        {
          items: [
            { link: '/permit/usage#basic-setup', text: 'Basic Setup' },
            { link: '/permit/usage#registering-permissions-with-define', text: 'define()' },
            { link: '/permit/usage#wildcards', text: 'Wildcards' },
            { link: '/permit/usage#role-inheritance', text: 'Role Inheritance' },
            { link: '/permit/usage#anonymous-users', text: 'Anonymous Users' },
            { link: '/permit/usage#checking-permissions', text: 'Checking Permissions' },
            { link: '/permit/usage#guard-api', text: 'Guard API' },
            { link: '/permit/usage#removing-and-resetting-state', text: 'State Lifecycle' },
            { link: '/permit/usage#best-practices', text: 'Best Practices' },
          ],
          link: '/permit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/permit/api#createpermit', text: 'createPermit()' },
            { link: '/permit/api#permit-interface', text: 'Permit Interface' },
            { link: '/permit/api#constants', text: 'Constants' },
            { link: '/permit/api#utilities', text: 'Utilities' },
            { link: '/permit/api#types', text: 'Types' },
          ],
          link: '/permit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/permit/examples/blog-roles', text: 'Blog Roles' },
            { link: '/permit/examples/bound-guard-in-ui-layer', text: 'Bound Guard in UI Layer' },
            { link: '/permit/examples/disabling-wildcard-fallback', text: 'Disabling Wildcard Fallback' },
            { link: '/permit/examples/inheritance-and-overrides', text: 'Inheritance and Overrides' },
            { link: '/permit/examples/logger-for-auditing', text: 'Logger for Auditing' },
            {
              link: '/permit/examples/snapshot-restore-for-test-isolation',
              text: 'Snapshot / Restore for Test Isolation',
            },
            { link: '/permit/examples/wildcard-action', text: 'Wildcard Action' },
          ],
          link: '/permit/examples',
          text: 'Examples',
        },
      ],
      '/routeit/': [
        { link: '/routeit/', text: 'Overview' },
        {
          items: [
            { link: '/routeit/usage#basic-usage', text: 'Basic Usage' },
            { link: '/routeit/usage#route-groups', text: 'Route Groups' },
            { link: '/routeit/usage#typed-prefix-params', text: 'Typed Prefix Params' },
            { link: '/routeit/usage#middleware', text: 'Middleware' },
            { link: '/routeit/usage#navigation', text: 'Navigation' },
            { link: '/routeit/usage#named-routes', text: 'Named Routes' },
            { link: '/routeit/usage#url-builder', text: 'URL Builder' },
            { link: '/routeit/usage#isactive', text: 'isActive' },
            { link: '/routeit/usage#state--subscriptions', text: 'State & Subscriptions' },
            { link: '/routeit/usage#error-handling', text: 'Error Handling' },
            { link: '/routeit/usage#view-transitions', text: 'View Transitions' },
          ],
          link: '/routeit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/routeit/api#createrouter-options', text: 'createRouter()' },
            { link: '/routeit/api#router', text: 'Router' },
            { link: '/routeit/api#types', text: 'Types' },
            { link: '/routeit/api#pattern-matching', text: 'Pattern Matching' },
          ],
          link: '/routeit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/routeit/examples/framework-integration', text: 'Framework Integration' },
            { link: '/routeit/examples/authentication', text: 'Authentication' },
            { link: '/routeit/examples/autostart', text: 'autoStart' },
            { link: '/routeit/examples/base-path-deployment', text: 'Base Path Deployment' },
            { link: '/routeit/examples/error-handling', text: 'Error Handling' },
            { link: '/routeit/examples/hash-fragment-navigation', text: 'Hash Fragment Navigation' },
            {
              link: '/routeit/examples/hash-mode-spa-without-server-config',
              text: 'Hash Mode (SPA without server config)',
            },
            { link: '/routeit/examples/lazy-loading', text: 'Lazy Loading' },
            { link: '/routeit/examples/middleware-only-routes', text: 'Middleware-only Routes' },
            { link: '/routeit/examples/named-routes-and-url-builder', text: 'Named Routes & URL Builder' },
            { link: '/routeit/examples/navigation-tracking-and-analytics', text: 'Navigation Tracking & Analytics' },
            { link: '/routeit/examples/page-titles-from-meta', text: 'Page Titles from Meta' },
            { link: '/routeit/examples/redirects', text: 'Redirects' },
            { link: '/routeit/examples/role-based-access-control', text: 'Role-based Access Control' },
            { link: '/routeit/examples/scroll-restoration', text: 'Scroll Restoration' },
            { link: '/routeit/examples/same-url-deduplication', text: 'Same-URL Deduplication' },
            { link: '/routeit/examples/spa-with-layout-selection', text: 'SPA with Layout Selection' },
            { link: '/routeit/examples/typed-group-prefix-params', text: 'Typed Group Prefix Params' },
            {
              link: '/routeit/examples/using-explicit-resource-management',
              text: '`using` — Explicit Resource Management',
            },
            { link: '/routeit/examples/view-transitions', text: 'View Transitions' },
            { link: '/routeit/examples/view-transitions-api', text: 'View Transitions API' },
            { link: '/routeit/examples/wildcard-routes', text: 'Wildcard Routes' },
          ],
          link: '/routeit/examples',
          text: 'Examples',
        },
      ],
      '/stateit/': [
        { link: '/stateit/', text: 'Overview' },
        {
          items: [
            { link: '/stateit/usage#signals', text: 'Signals' },
            { link: '/stateit/usage#effects', text: 'Effects' },
            { link: '/stateit/usage#computed', text: 'Computed' },
            { link: '/stateit/usage#derived', text: 'derived' },
            { link: '/stateit/usage#writable', text: 'writable' },
            { link: '/stateit/usage#watch-signals', text: 'watch' },
            { link: '/stateit/usage#batch-signals', text: 'batch' },
            { link: '/stateit/usage#stores', text: 'Stores' },
            { link: '/stateit/usage#derived-slices', text: 'Derived Slices' },
            { link: '/stateit/usage#watching-state', text: 'Watching State' },
            { link: '/stateit/usage#batching', text: 'Batching' },
            { link: '/stateit/usage#global-configuration', text: 'Configuration' },
            { link: '/stateit/usage#testing', text: 'Testing' },
          ],
          link: '/stateit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/stateit/api#signal-primitives', text: 'Signal Primitives' },
            { link: '/stateit/api#store-functions', text: 'Store Functions' },
            { link: '/stateit/api#signal-types', text: 'Signal Types' },
            { link: '/stateit/api#store-types', text: 'Store Types' },
            { link: '/stateit/api#notification-timing', text: 'Notification Timing' },
            { link: '/stateit/api#testing-utilities', text: 'Testing Utilities' },
          ],
          link: '/stateit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/stateit/examples/signals', text: 'Signals' },
            { link: '/stateit/examples/stores', text: 'Stores' },
            { link: '/stateit/examples/framework-integration', text: 'Framework Integration' },
            {
              link: '/stateit/examples/pattern-batch-for-complex-mutations',
              text: 'Pattern: Batch for Complex Mutations',
            },
            {
              link: '/stateit/examples/pattern-nextvalue-in-async-workflows',
              text: 'Pattern: `nextValue` in Async Workflows',
            },
            { link: '/stateit/examples/pattern-shared-module-store', text: 'Pattern: Shared Module Store' },
          ],
          link: '/stateit/examples',
          text: 'Examples',
        },
      ],
      '/timit/': [
        { link: '/timit/', text: 'Overview' },
        {
          items: [
            { link: '/timit/usage#parsing-inputs', text: 'Parsing Inputs' },
            { link: '/timit/usage#time-zone-conversion', text: 'Time Zone Conversion' },
            { link: '/timit/usage#date-time-arithmetic', text: 'Date-Time Arithmetic' },
            { link: '/timit/usage#duration-differences', text: 'Duration Differences' },
            { link: '/timit/usage#formatting', text: 'Formatting' },
          ],
          link: '/timit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/timit/api#exports', text: 'Exports' },
            { link: '/timit/api#core-types', text: 'Core Types' },
            { link: '/timit/api#behavior-notes', text: 'Behavior Notes' },
          ],
          link: '/timit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/timit/examples/timezone-conversion', text: 'Timezone Conversion' },
            { link: '/timit/examples/dst-safe-arithmetic', text: 'DST-safe Arithmetic' },
            { link: '/timit/examples/locale-formatting', text: 'Locale Formatting' },
          ],
          link: '/timit/examples',
          text: 'Examples',
        },
      ],
      '/toolkit/': [
        { link: '/toolkit/', text: 'Overview' },
        {
          items: [
            { link: '/toolkit/usage#basic-usage', text: 'Basic Usage' },
            { link: '/toolkit/usage#common-patterns', text: 'Common Patterns' },
            { link: '/toolkit/usage#advanced-usage', text: 'Advanced Usage' },
            { link: '/toolkit/usage#framework-integration', text: 'Framework Integration' },
            { link: '/toolkit/usage#best-practices', text: 'Best Practices' },
            { link: '/toolkit/usage#performance-tips', text: 'Performance' },
          ],
          link: '/toolkit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/toolkit/api#array-utilities', text: 'Array' },
            { link: '/toolkit/api#object-utilities', text: 'Object' },
            { link: '/toolkit/api#string-utilities', text: 'String' },
            { link: '/toolkit/api#function-utilities', text: 'Function' },
            { link: '/toolkit/api#async-utilities', text: 'Async' },
            { link: '/toolkit/api#math-utilities', text: 'Math' },
            { link: '/toolkit/api#money-utilities', text: 'Money' },
            { link: '/toolkit/api#date-utilities', text: 'Date' },
            { link: '/toolkit/api#random-utilities', text: 'Random' },
            { link: '/toolkit/api#typed-utilities', text: 'Typed' },
          ],
          link: '/toolkit/api',
          text: 'API Reference',
        },
        {
          items: [
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/array/chunk', text: 'chunk' },
                { link: '/toolkit/examples/array/contains', text: 'contains' },
                { link: '/toolkit/examples/array/fold', text: 'fold' },
                { link: '/toolkit/examples/array/group', text: 'group' },
                { link: '/toolkit/examples/array/keyBy', text: 'keyBy' },
                { link: '/toolkit/examples/array/list', text: 'list' },
                { link: '/toolkit/examples/array/pick', text: 'pick' },
                { link: '/toolkit/examples/array/remoteList', text: 'remoteList' },
                { link: '/toolkit/examples/array/replace', text: 'replace' },
                { link: '/toolkit/examples/array/rotate', text: 'rotate' },
                { link: '/toolkit/examples/array/search', text: 'search' },
                { link: '/toolkit/examples/array/select', text: 'select' },
                { link: '/toolkit/examples/array/sort', text: 'sort' },
                { link: '/toolkit/examples/array/toggle', text: 'toggle' },
                { link: '/toolkit/examples/array/uniq', text: 'uniq' },
              ],
              link: '/toolkit/examples/array',
              text: 'Array',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/async/attempt', text: 'attempt' },
                { link: '/toolkit/examples/async/defer', text: 'defer' },
                { link: '/toolkit/examples/async/parallel', text: 'parallel' },
                { link: '/toolkit/examples/async/pool', text: 'pool' },
                { link: '/toolkit/examples/async/queue', text: 'queue' },
                { link: '/toolkit/examples/async/race', text: 'race' },
                { link: '/toolkit/examples/async/retry', text: 'retry' },
                { link: '/toolkit/examples/async/sleep', text: 'sleep' },
                { link: '/toolkit/examples/async/waitFor', text: 'waitFor' },
              ],
              link: '/toolkit/examples/async',
              text: 'Async',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/string/camelCase', text: 'camelCase' },
                { link: '/toolkit/examples/string/kebabCase', text: 'kebabCase' },
                { link: '/toolkit/examples/string/pascalCase', text: 'pascalCase' },
                { link: '/toolkit/examples/string/similarity', text: 'similarity' },
                { link: '/toolkit/examples/string/snakeCase', text: 'snakeCase' },
                { link: '/toolkit/examples/string/truncate', text: 'truncate' },
              ],
              link: '/toolkit/examples/string',
              text: 'String',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/object/cache', text: 'cache' },
                { link: '/toolkit/examples/object/diff', text: 'diff' },
                { link: '/toolkit/examples/object/merge', text: 'merge' },
                { link: '/toolkit/examples/object/parseJSON', text: 'parseJSON' },
                { link: '/toolkit/examples/object/path', text: 'path' },
                { link: '/toolkit/examples/object/proxy', text: 'proxy' },
                { link: '/toolkit/examples/object/prune', text: 'prune' },
                { link: '/toolkit/examples/object/seek', text: 'seek' },
              ],
              link: '/toolkit/examples/object',
              text: 'Object',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/date/expires', text: 'expires' },
                { link: '/toolkit/examples/date/interval', text: 'interval' },
                { link: '/toolkit/examples/date/timeDiff', text: 'timeDiff' },
              ],
              link: '/toolkit/examples/date',
              text: 'Date',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/function/assert', text: 'assert' },
                { link: '/toolkit/examples/function/assertParams', text: 'assertParams' },
                { link: '/toolkit/examples/function/compare', text: 'compare' },
                { link: '/toolkit/examples/function/compareBy', text: 'compareBy' },
                { link: '/toolkit/examples/function/compose', text: 'compose' },
                { link: '/toolkit/examples/function/curry', text: 'curry' },
                { link: '/toolkit/examples/function/debounce', text: 'debounce' },
                { link: '/toolkit/examples/function/fp', text: 'fp' },
                { link: '/toolkit/examples/function/memo', text: 'memo' },
                { link: '/toolkit/examples/function/once', text: 'once' },
                { link: '/toolkit/examples/function/pipe', text: 'pipe' },
                { link: '/toolkit/examples/function/throttle', text: 'throttle' },
              ],
              link: '/toolkit/examples/function',
              text: 'Function',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/math/abs', text: 'abs' },
                { link: '/toolkit/examples/math/allocate', text: 'allocate' },
                { link: '/toolkit/examples/math/average', text: 'average' },
                { link: '/toolkit/examples/math/clamp', text: 'clamp' },
                { link: '/toolkit/examples/math/distribute', text: 'distribute' },
                { link: '/toolkit/examples/math/linspace', text: 'linspace' },
                { link: '/toolkit/examples/math/max', text: 'max' },
                { link: '/toolkit/examples/math/median', text: 'median' },
                { link: '/toolkit/examples/math/min', text: 'min' },
                { link: '/toolkit/examples/math/percent', text: 'percent' },
                { link: '/toolkit/examples/math/range', text: 'range' },
                { link: '/toolkit/examples/math/round', text: 'round' },
                { link: '/toolkit/examples/math/sum', text: 'sum' },
              ],
              link: '/toolkit/examples/math',
              text: 'Math',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/money/currency', text: 'currency' },
                { link: '/toolkit/examples/money/exchange', text: 'exchange' },
              ],
              link: '/toolkit/examples/money',
              text: 'Money',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/random/draw', text: 'draw' },
                { link: '/toolkit/examples/random/random', text: 'random' },
                { link: '/toolkit/examples/random/shuffle', text: 'shuffle' },
                { link: '/toolkit/examples/random/uuid', text: 'uuid' },
              ],
              link: '/toolkit/examples/random',
              text: 'Random',
            },
            {
              collapsed: true,
              items: [
                { link: '/toolkit/examples/typed/is', text: 'is' },
                { link: '/toolkit/examples/typed/isArray', text: 'is.array' },
                { link: '/toolkit/examples/typed/isBoolean', text: 'is.boolean' },
                { link: '/toolkit/examples/typed/isDate', text: 'is.date' },
                { link: '/toolkit/examples/typed/isDefined', text: 'is.defined' },
                { link: '/toolkit/examples/typed/isEmpty', text: 'is.empty' },
                { link: '/toolkit/examples/typed/isEqual', text: 'is.equal' },
                { link: '/toolkit/examples/typed/isEven', text: 'is.even' },
                { link: '/toolkit/examples/typed/isFunction', text: 'is.fn' },
                { link: '/toolkit/examples/typed/isMatch', text: 'is.match' },
                { link: '/toolkit/examples/typed/isNegative', text: 'is.negative' },
                { link: '/toolkit/examples/typed/isNil', text: 'is.nil' },
                { link: '/toolkit/examples/typed/isNumber', text: 'is.number' },
                { link: '/toolkit/examples/typed/isObject', text: 'is.object' },
                { link: '/toolkit/examples/typed/isOdd', text: 'is.odd' },
                { link: '/toolkit/examples/typed/isPositive', text: 'is.positive' },
                { link: '/toolkit/examples/typed/isPrimitive', text: 'is.primitive' },
                { link: '/toolkit/examples/typed/isPromise', text: 'is.promise' },
                { link: '/toolkit/examples/typed/isRegex', text: 'is.regex' },
                { link: '/toolkit/examples/typed/isString', text: 'is.string' },
                { link: '/toolkit/examples/typed/isWithin', text: 'is.within' },
                { link: '/toolkit/examples/typed/isZero', text: 'is.zero' },
                { link: '/toolkit/examples/typed/typeOf', text: 'is.typeOf' },
              ],
              link: '/toolkit/examples/typed',
              text: 'Typed',
            },
          ],
          link: '/toolkit/examples',
          text: 'Examples',
        },
      ],
      '/validit/': [
        { link: '/validit/', text: 'Overview' },
        {
          items: [
            { link: '/validit/usage#basic-usage', text: 'Basic Usage' },
            { link: '/validit/usage#primitive-schemas', text: 'Primitives' },
            { link: '/validit/usage#complex-schemas', text: 'Complex Schemas' },
            { link: '/validit/usage#validation-flow', text: 'Validation Flow' },
            { link: '/validit/usage#modifiers', text: 'Modifiers' },
            { link: '/validit/usage#refinements', text: 'Refinements' },
            { link: '/validit/usage#transform-and-preprocess', text: 'Transform & Preprocess' },
            { link: '/validit/usage#message-configuration', text: 'Message Configuration' },
            { link: '/validit/usage#error-handling', text: 'Error Handling' },
            { link: '/validit/usage#type-inference', text: 'Type Inference' },
          ],
          link: '/validit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/validit/api#package-exports', text: 'Package Exports' },
            { link: '/validit/api#v-factory', text: 'v Factory' },
            { link: '/validit/api#schema-base-methods', text: 'Schema Methods' },
            { link: '/validit/api#global-configuration', text: 'Configuration' },
            { link: '/validit/api#types', text: 'Types' },
            { link: '/validit/api#errors', text: 'Errors' },
          ],
          link: '/validit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/validit/examples/forms', text: 'Forms' },
            { link: '/validit/examples/api', text: 'API' },
            { link: '/validit/examples/async', text: 'Async' },
            { link: '/validit/examples/unions', text: 'Unions & Variant' },
          ],
          link: '/validit/examples',
          text: 'Examples',
        },
      ],
      '/virtualit/': [
        { link: '/virtualit/', text: 'Overview' },
        {
          items: [
            { link: '/virtualit/usage#dom-layout-requirements', text: 'DOM Layout' },
            { link: '/virtualit/usage#fixed-heights', text: 'Fixed Heights' },
            { link: '/virtualit/usage#variable-heights-estimator', text: 'Variable Heights (Estimator)' },
            { link: '/virtualit/usage#variable-heights-measured', text: 'Variable Heights' },
            { link: '/virtualit/usage#overscan', text: 'Overscan' },
            { link: '/virtualit/usage#updating-the-count', text: 'Updating Count' },
            { link: '/virtualit/usage#switching-row-density', text: 'Row Density' },
            { link: '/virtualit/usage#programmatic-scrolling', text: 'Programmatic Scrolling' },
            { link: '/virtualit/usage#invalidating-measurements', text: 'Invalidating Measurements' },
            { link: '/virtualit/usage#lifecycle-attach-and-destroy', text: 'Lifecycle' },
            { link: '/virtualit/usage#explicit-resource-management', text: 'Resource Management' },
            { link: '/virtualit/usage#framework-integration', text: 'Framework Integration' },
          ],
          link: '/virtualit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/virtualit/api#package-exports', text: 'Package Exports' },
            { link: '/virtualit/api#core-functions', text: 'Core Functions' },
            { link: '/virtualit/api#virtualizer-class', text: 'Virtualizer Class' },
            { link: '/virtualit/api#properties', text: 'Properties' },
            { link: '/virtualit/api#methods', text: 'Methods' },
            { link: '/virtualit/api#types', text: 'Types' },
          ],
          link: '/virtualit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/virtualit/examples/basic-fixed-height-list', text: 'Basic Fixed-Height List' },
            {
              link: '/virtualit/examples/density-toggle-compact-comfortable',
              text: 'Density Toggle (Compact / Comfortable)',
            },
            {
              link: '/virtualit/examples/explicit-resource-management-using',
              text: 'Explicit Resource Management (`using`)',
            },
            { link: '/virtualit/examples/grouped-list-headers-plus-rows', text: 'Grouped List (Headers + Rows)' },
            { link: '/virtualit/examples/infinite-scroll-load-more', text: 'Infinite Scroll (Load More)' },
            { link: '/virtualit/examples/keyboard-navigation', text: 'Keyboard Navigation' },
            { link: '/virtualit/examples/restore-scroll-position', text: 'Restore Scroll Position' },
            {
              link: '/virtualit/examples/using-virtualizer-directly-without-createvirtualizer',
              text: 'Using `Virtualizer` Directly (Without `createVirtualizer`)',
            },
            { link: '/virtualit/examples/variable-height-with-measurement', text: 'Variable Height with Measurement' },
          ],
          link: '/virtualit/examples',
          text: 'Examples',
        },
      ],
      '/wireit/': [
        { link: '/wireit/', text: 'Overview' },
        {
          items: [
            { link: '/wireit/usage#tokens', text: 'Tokens' },
            { link: '/wireit/usage#providers', text: 'Providers' },
            { link: '/wireit/usage#lifetimes', text: 'Lifetimes' },
            { link: '/wireit/usage#child-containers-and-hierarchy', text: 'Child Containers' },
            { link: '/wireit/usage#scoped-execution', text: 'Scoped Execution' },
            { link: '/wireit/usage#aliases', text: 'Aliases' },
            { link: '/wireit/usage#async-resolution', text: 'Async Resolution' },
            { link: '/wireit/usage#batch-resolution', text: 'Batch Resolution' },
            { link: '/wireit/usage#optional-resolution', text: 'Optional Resolution' },
            { link: '/wireit/usage#snapshot--restore', text: 'Snapshot / Restore' },
            { link: '/wireit/usage#testing', text: 'Testing' },
            { link: '/wireit/usage#debug', text: 'Debug' },
          ],
          link: '/wireit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/wireit/api#package-exports', text: 'Package Exports' },
            { link: '/wireit/api#createtoken-description', text: 'createToken()' },
            { link: '/wireit/api#createcontainer', text: 'createContainer()' },
            { link: '/wireit/api#createtestcontainer-base', text: 'createTestContainer()' },
            { link: '/wireit/api#container-registration', text: 'Registration' },
            { link: '/wireit/api#container-resolution', text: 'Resolution' },
            { link: '/wireit/api#container-hierarchy', text: 'Hierarchy' },
            { link: '/wireit/api#container-lifecycle', text: 'Lifecycle' },
            { link: '/wireit/api#container-testing', text: 'Testing' },
            { link: '/wireit/api#types', text: 'Types' },
            { link: '/wireit/api#errors', text: 'Errors' },
          ],
          link: '/wireit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/wireit/examples/aliases', text: 'Aliases' },
            { link: '/wireit/examples/async-providers', text: 'Async Providers' },
            { link: '/wireit/examples/basic-setup', text: 'Basic Setup' },
            { link: '/wireit/examples/batch-resolution', text: 'Batch Resolution' },
            { link: '/wireit/examples/child-containers', text: 'Child Containers' },
            { link: '/wireit/examples/debug', text: 'Debug' },
            { link: '/wireit/examples/dispose-lifecycle', text: 'Dispose Lifecycle' },
            { link: '/wireit/examples/lifetimes', text: 'Lifetimes' },
            { link: '/wireit/examples/testing', text: 'Testing' },
          ],
          link: '/wireit/examples',
          text: 'Examples',
        },
      ],
      '/workit/': [
        { link: '/workit/', text: 'Overview' },
        {
          items: [
            { link: '/workit/usage#task-functions', text: 'Task Functions' },
            { link: '/workit/usage#single-worker', text: 'Single Worker' },
            { link: '/workit/usage#worker-pool', text: 'Worker Pool' },
            { link: '/workit/usage#timeouts', text: 'Timeouts' },
            { link: '/workit/usage#abortsignal', text: 'AbortSignal' },
            { link: '/workit/usage#transferables', text: 'Transferables' },
            { link: '/workit/usage#worker-status', text: 'Worker Status' },
            { link: '/workit/usage#isnative', text: 'isNative' },
            { link: '/workit/usage#fallback-mode', text: 'Fallback Mode' },
            { link: '/workit/usage#external-scripts', text: 'External Scripts' },
            { link: '/workit/usage#testing', text: 'Testing' },
          ],
          link: '/workit/usage',
          text: 'Usage Guide',
        },
        {
          items: [
            { link: '/workit/api#package-exports', text: 'Package Exports' },
            { link: '/workit/api#types', text: 'Types' },
            { link: '/workit/api#createworker', text: 'createWorker()' },
            { link: '/workit/api#workerhandle-interface', text: 'WorkerHandle Interface' },
            { link: '/workit/api#error-classes', text: 'Error Classes' },
            { link: '/workit/api#testing-utilities', text: 'Testing Utilities' },
          ],
          link: '/workit/api',
          text: 'API Reference',
        },
        {
          items: [
            { link: '/workit/examples/cancellable-batch', text: 'Cancellable Batch' },
            { link: '/workit/examples/data-transformation-pipeline', text: 'Data Pipeline' },
            { link: '/workit/examples/fibonacci-with-pool-and-timeout', text: 'Fibonacci Pool' },
            { link: '/workit/examples/image-processing', text: 'Image Processing' },
            { link: '/workit/examples/react-integration', text: 'React Integration' },
            { link: '/workit/examples/testing-with-createtestworker', text: 'Testing' },
            { link: '/workit/examples/using-external-scripts-importscripts', text: 'importScripts' },
          ],
          link: '/workit/examples',
          text: 'Examples',
        },
      ],
    }),
    socialLinks: [{ icon: 'github', link: 'https://github.com/helmuthdu/vielzeug' }],
  },
  title: 'Vielzeug',
  vite: {
    build: {
      cssMinify: 'lightningcss',
    },
    css: {
      lightningcss: {
        targets: browserslistToTargets(browserslist('>= 0.25%')),
      },
      transformer: 'lightningcss',
    },
    resolve: {
      alias: {
        '@vielzeug/buildit': resolve(__dirname, '../../packages/buildit/src'),
        '@vielzeug/craftit': resolve(__dirname, '../../packages/craftit/src'),
        '@vielzeug/deposit': resolve(__dirname, '../../packages/deposit/src'),
        '@vielzeug/dragit': resolve(__dirname, '../../packages/dragit/src'),
        '@vielzeug/eventit': resolve(__dirname, '../../packages/eventit/src'),
        '@vielzeug/fetchit': resolve(__dirname, '../../packages/fetchit/src'),
        '@vielzeug/floatit': resolve(__dirname, '../../packages/floatit/src'),
        '@vielzeug/formit': resolve(__dirname, '../../packages/formit/src'),
        '@vielzeug/i18nit': resolve(__dirname, '../../packages/i18nit/src'),
        '@vielzeug/logit': resolve(__dirname, '../../packages/logit/src'),
        '@vielzeug/permit': resolve(__dirname, '../../packages/permit/src'),
        '@vielzeug/routeit': resolve(__dirname, '../../packages/routeit/src'),
        '@vielzeug/stateit': resolve(__dirname, '../../packages/stateit/src'),
        '@vielzeug/timit': resolve(__dirname, '../../packages/timit/src'),
        '@vielzeug/toolkit': resolve(__dirname, '../../packages/toolkit/src'),
        '@vielzeug/validit': resolve(__dirname, '../../packages/validit/src'),
        '@vielzeug/virtualit': resolve(__dirname, '../../packages/virtualit/src'),
        '@vielzeug/wireit': resolve(__dirname, '../../packages/wireit/src'),
        '@vielzeug/workit': resolve(__dirname, '../../packages/workit/src'),
      },
    },
  },
  vue: {
    template: {
      compilerOptions: {
        isCustomElement: (tag) => tag.startsWith('bit-'),
      },
    },
  },
} as UserConfig<ThemeConfig>);
