import { defineConfig } from 'vitepress';

export default defineConfig({
  base: '/vielzeug',
  description: 'Documentation for the Vielzeug monorepo',
  head: [
    ['meta', { content: '#008dfc', name: 'theme-color' }],
    ['meta', { content: 'yes', name: 'apple-mobile-web-app-capable' }],
    ['meta', { content: 'black', name: 'apple-mobile-web-app-status-bar-style' }],
  ],
  ignoreDeadLinks: true,
  sitemap: {
    hostname: 'https://helmuthdu.github.io/vielzeug',
    transformItems: (items) => {
      return items.map((item) => {
        return {
          ...item,
          url: `vielzeug/${item.url}`, // Fix sitemap URLs
        };
      });
    },
  },
  themeConfig: {
    logo: '/logo_main.svg',
    nav: [
      { link: '/toolkit/', text: 'Toolkit' },
      { link: '/deposit/', text: 'Deposit' },
      { link: '/fetchit/', text: 'Fetchit' },
      { link: '/formit/', text: 'Formit' },
      { link: '/i18nit/', text: 'i18nit' },
      { link: '/logit/', text: 'Logit' },
      { link: '/permit/', text: 'Permit' },
      { link: '/validit/', text: 'Validit' },
      { link: '/repl', text: 'REPL' },
    ],
    search: {
      provider: 'local',
    },
    sidebar: {
      '/deposit/': [
        { link: '/deposit/', text: 'Overview' },
        { link: '/deposit/api', text: 'API Reference' },
        { link: '/deposit/usage', text: 'Usage' },
        { link: '/deposit/examples', text: 'Examples' },
      ],
      '/fetchit/': [
        { link: '/fetchit/', text: 'Overview' },
        { link: '/fetchit/api', text: 'API Reference' },
        { link: '/fetchit/usage', text: 'Usage' },
        { link: '/fetchit/examples', text: 'Examples' },
      ],
      '/formit/': [
        { link: '/formit/', text: 'Overview' },
        { link: '/formit/api', text: 'API Reference' },
        { link: '/formit/usage', text: 'Usage' },
        { link: '/formit/examples', text: 'Examples' },
      ],
      '/i18nit/': [
        { link: '/i18nit/', text: 'Overview' },
        { link: '/i18nit/api', text: 'API Reference' },
        { link: '/i18nit/usage', text: 'Usage' },
        { link: '/i18nit/examples', text: 'Examples' },
      ],
      '/logit/': [
        { link: '/logit/', text: 'Overview' },
        { link: '/logit/api', text: 'API Reference' },
        { link: '/logit/usage', text: 'Usage' },
        { link: '/logit/examples', text: 'Examples' },
      ],
      '/permit/': [
        { link: '/permit/', text: 'Overview' },
        { link: '/permit/api', text: 'API Reference' },
        { link: '/permit/usage', text: 'Usage' },
        { link: '/permit/examples', text: 'Examples' },
      ],
      '/toolkit/': [
        { link: '/toolkit/', text: 'Overview' },
        { link: '/toolkit/api', text: 'API Reference' },
        { link: '/toolkit/usage', text: 'Usage' },
        {
          items: [
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/array/aggregate', text: 'aggregate' },
                { link: '/toolkit/examples/array/alternate', text: 'alternate' },
                { link: '/toolkit/examples/array/arrange', text: 'arrange' },
                { link: '/toolkit/examples/array/chunk', text: 'chunk' },
                { link: '/toolkit/examples/array/compact', text: 'compact' },
                { link: '/toolkit/examples/array/contains', text: 'contains' },
                { link: '/toolkit/examples/array/every', text: 'every' },
                { link: '/toolkit/examples/array/filter', text: 'filter' },
                { link: '/toolkit/examples/array/find', text: 'find' },
                { link: '/toolkit/examples/array/findIndex', text: 'findIndex' },
                { link: '/toolkit/examples/array/findLast', text: 'findLast' },
                { link: '/toolkit/examples/array/flatten', text: 'flatten' },
                { link: '/toolkit/examples/array/group', text: 'group' },
                { link: '/toolkit/examples/array/list', text: 'list' },
                { link: '/toolkit/examples/array/map', text: 'map' },
                { link: '/toolkit/examples/array/pick', text: 'pick' },
                { link: '/toolkit/examples/array/reduce', text: 'reduce' },
                { link: '/toolkit/examples/array/remoteList', text: 'remoteList' },
                { link: '/toolkit/examples/array/search', text: 'search' },
                { link: '/toolkit/examples/array/select', text: 'select' },
                { link: '/toolkit/examples/array/shift', text: 'shift' },
                { link: '/toolkit/examples/array/some', text: 'some' },
                { link: '/toolkit/examples/array/sort', text: 'sort' },
                { link: '/toolkit/examples/array/substitute', text: 'substitute' },
                { link: '/toolkit/examples/array/uniq', text: 'uniq' },
              ],
              link: '/toolkit/examples/array',
              text: 'Array',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/async/attempt', text: 'attempt' },
                { link: '/toolkit/examples/async/defer', text: 'defer' },
                { link: '/toolkit/examples/async/delay', text: 'delay' },
                { link: '/toolkit/examples/async/parallel', text: 'parallel' },
                { link: '/toolkit/examples/async/pool', text: 'pool' },
                { link: '/toolkit/examples/async/predict', text: 'predict' },
                { link: '/toolkit/examples/async/queue', text: 'queue' },
                { link: '/toolkit/examples/async/race', text: 'race' },
                { link: '/toolkit/examples/async/retry', text: 'retry' },
                { link: '/toolkit/examples/async/sleep', text: 'sleep' },
                { link: '/toolkit/examples/async/waitFor', text: 'waitFor' },
              ],
              link: '/toolkit/examples/async',
              text: 'Async',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/string/camelCase', text: 'camelCase' },
                { link: '/toolkit/examples/string/kebabCase', text: 'kebabCase' },
                { link: '/toolkit/examples/string/pascalCase', text: 'pascalCase' },
                { link: '/toolkit/examples/string/similarity', text: 'similarity' },
                { link: '/toolkit/examples/string/snakeCase', text: 'snakeCase' },
                { link: '/toolkit/examples/string/truncate', text: 'truncate' },
              ],
              link: '/toolkit/examples/string',
              text: 'String',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/object/clone', text: 'clone' },
                { link: '/toolkit/examples/object/diff', text: 'diff' },
                { link: '/toolkit/examples/object/entries', text: 'entries' },
                { link: '/toolkit/examples/object/keys', text: 'keys' },
                { link: '/toolkit/examples/object/merge', text: 'merge' },
                { link: '/toolkit/examples/object/parseJSON', text: 'parseJSON' },
                { link: '/toolkit/examples/object/path', text: 'path' },
                { link: '/toolkit/examples/object/seek', text: 'seek' },
                { link: '/toolkit/examples/object/values', text: 'values' },
              ],
              link: '/toolkit/examples/object',
              text: 'Object',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/date/expires', text: 'expires' },
                { link: '/toolkit/examples/date/interval', text: 'interval' },
                { link: '/toolkit/examples/date/timeDiff', text: 'timeDiff' },
              ],
              link: '/toolkit/examples/date',
              text: 'Date',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/function/assert', text: 'assert' },
                { link: '/toolkit/examples/function/assertParams', text: 'assertParams' },
                { link: '/toolkit/examples/function/compare', text: 'compare' },
                { link: '/toolkit/examples/function/compareBy', text: 'compareBy' },
                { link: '/toolkit/examples/function/compose', text: 'compose' },
                { link: '/toolkit/examples/function/curry', text: 'curry' },
                { link: '/toolkit/examples/function/debounce', text: 'debounce' },
                { link: '/toolkit/examples/function/fp', text: 'fp' },
                { link: '/toolkit/examples/function/memo', text: 'memo' },
                { link: '/toolkit/examples/function/once', text: 'once' },
                { link: '/toolkit/examples/function/pipe', text: 'pipe' },
                { link: '/toolkit/examples/function/proxy', text: 'proxy' },
                { link: '/toolkit/examples/function/prune', text: 'prune' },
                { link: '/toolkit/examples/function/throttle', text: 'throttle' },
                { link: '/toolkit/examples/function/worker', text: 'worker' },
              ],
              link: '/toolkit/examples/function',
              text: 'Function',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/math/abs', text: 'abs' },
                { link: '/toolkit/examples/math/add', text: 'add' },
                { link: '/toolkit/examples/math/allocate', text: 'allocate' },
                { link: '/toolkit/examples/math/average', text: 'average' },
                { link: '/toolkit/examples/math/boil', text: 'boil' },
                { link: '/toolkit/examples/math/clamp', text: 'clamp' },
                { link: '/toolkit/examples/math/distribute', text: 'distribute' },
                { link: '/toolkit/examples/math/divide', text: 'divide' },
                { link: '/toolkit/examples/math/max', text: 'max' },
                { link: '/toolkit/examples/math/median', text: 'median' },
                { link: '/toolkit/examples/math/min', text: 'min' },
                { link: '/toolkit/examples/math/multiply', text: 'multiply' },
                { link: '/toolkit/examples/math/range', text: 'range' },
                { link: '/toolkit/examples/math/rate', text: 'rate' },
                { link: '/toolkit/examples/math/round', text: 'round' },
                { link: '/toolkit/examples/math/subtract', text: 'subtract' },
                { link: '/toolkit/examples/math/sum', text: 'sum' },
              ],
              link: '/toolkit/examples/math',
              text: 'Math',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/money/currency', text: 'currency' },
                { link: '/toolkit/examples/money/exchange', text: 'exchange' },
              ],
              link: '/toolkit/examples/money',
              text: 'Money',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/random/draw', text: 'draw' },
                { link: '/toolkit/examples/random/random', text: 'random' },
                { link: '/toolkit/examples/random/shuffle', text: 'shuffle' },
                { link: '/toolkit/examples/random/uuid', text: 'uuid' },
              ],
              link: '/toolkit/examples/random',
              text: 'Random',
            },
            {
              collapsed: false,
              items: [
                { link: '/toolkit/examples/typed/ge', text: 'ge' },
                { link: '/toolkit/examples/typed/gt', text: 'gt' },
                { link: '/toolkit/examples/typed/is', text: 'is' },
                { link: '/toolkit/examples/typed/isArray', text: 'isArray' },
                { link: '/toolkit/examples/typed/isBoolean', text: 'isBoolean' },
                { link: '/toolkit/examples/typed/isDate', text: 'isDate' },
                { link: '/toolkit/examples/typed/isDefined', text: 'isDefined' },
                { link: '/toolkit/examples/typed/isEmpty', text: 'isEmpty' },
                { link: '/toolkit/examples/typed/isEqual', text: 'isEqual' },
                { link: '/toolkit/examples/typed/isEven', text: 'isEven' },
                { link: '/toolkit/examples/typed/isFunction', text: 'isFunction' },
                { link: '/toolkit/examples/typed/isMatch', text: 'isMatch' },
                { link: '/toolkit/examples/typed/isNegative', text: 'isNegative' },
                { link: '/toolkit/examples/typed/isNil', text: 'isNil' },
                { link: '/toolkit/examples/typed/isNumber', text: 'isNumber' },
                { link: '/toolkit/examples/typed/isObject', text: 'isObject' },
                { link: '/toolkit/examples/typed/isOdd', text: 'isOdd' },
                { link: '/toolkit/examples/typed/isPositive', text: 'isPositive' },
                { link: '/toolkit/examples/typed/isPrimitive', text: 'isPrimitive' },
                { link: '/toolkit/examples/typed/isPromise', text: 'isPromise' },
                { link: '/toolkit/examples/typed/isRegex', text: 'isRegex' },
                { link: '/toolkit/examples/typed/isString', text: 'isString' },
                { link: '/toolkit/examples/typed/isWithin', text: 'isWithin' },
                { link: '/toolkit/examples/typed/isZero', text: 'isZero' },
                { link: '/toolkit/examples/typed/le', text: 'le' },
                { link: '/toolkit/examples/typed/lt', text: 'lt' },
                { link: '/toolkit/examples/typed/typeOf', text: 'typeOf' },
              ],
              link: '/toolkit/examples/typed',
              text: 'Typed',
            },
          ],
          text: 'API',
        },
      ],
      '/validit/': [
        { link: '/validit/', text: 'Overview' },
        { link: '/validit/api', text: 'API Reference' },
        { link: '/validit/usage', text: 'Usage' },
        { link: '/validit/examples', text: 'Examples' },
      ],
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/helmuthdu/vielzeug' }],
  },
  title: 'Vielzeug',
});
