/** Flush all pending microtasks and macro-tasks so async state updates settle. */
export async function settle(): Promise<void> {
  // Yield to the event loop multiple times to flush queued microtasks and
  // promise continuations. Using await in a loop ensures each pass fully
  // resolves any chained microtasks generated by previous passes.
  for (let i = 0; i < 10; i++) {
    await new Promise<void>((resolve) => setTimeout(resolve, 0));
  }
}

export function createDeferred<T = void>(): {
  promise: Promise<T>;
  resolve: (value: T | PromiseLike<T>) => void;
} {
  let resolve!: (value: T | PromiseLike<T>) => void;
  const promise = new Promise<T>((resolvePromise) => {
    resolve = resolvePromise;
  });

  return { promise, resolve };
}
