/**
 * Curated REPL display metadata that genuinely can't be derived from source: a one-line human
 * description per package, and arsenal's fine-grained function categories (every other package
 * gets a single implicit "Exports" category — see REPLReference.vue). Kept in its own file,
 * separate from generate-repl-registry.ts's AST-manipulation logic, so updating a description
 * or re-categorizing a function is a one-line content edit, not a change to a 400-line
 * TS-compiler-API script.
 */

export const DESCRIPTIONS: Record<string, string> = {
  arsenal: 'Utility library with functions for arrays, objects, and more.',
  clockwork: 'Typed finite state machines with guards, async invokes, and more.',
  coins: 'Currency formatting and exchange utilities for monetary arithmetic.',
  conduit: 'Lightweight dependency injection container with IoC principles.',
  courier: 'Advanced HTTP client with caching, retries, mutations, and more.',
  dnd: 'Drag-and-drop primitives with file filtering and more.',
  familiar: 'Web Worker pool abstraction with queuing, timeout, and more.',
  flux: 'Composable reactive streams with a full operator library and ecosystem adapters.',
  forge: 'Form state management with reactive fields and async validation.',
  herald: 'Publish/Subscribe event bus with async support.',
  keymap: 'Headless keyboard shortcut manager with chord sequences, context guards, and disposable bindings.',
  ledger: 'Async undo/redo command stack with serialised queueing and Ripple reactive signals.',
  lingua: 'Internationalization library with TypeScript support.',
  orbit: 'Lightweight floating-element positioning for elements.',
  pulse: 'WebSocket client with auto-reconnect, message buffering, and more.',
  ripple: 'Reactive state based on signals, with stores, derived state, and more.',
  rune: 'Structured logger with level filtering, scoped namespaces, and more.',
  sandbox: 'Sandboxed iframe runtime with typed postMessage state bridge.',
  scout: 'Trigram fuzzy-search index with match highlighting and reactive layer.',
  scroll: 'Virtual list engine for performant rendering of large datasets.',
  sourcerer: 'Reactive query sources with pagination and URL state sync.',
  spell: 'Type-safe schema validation with advanced error handling.',
  tempo: 'Timezone-aware date/time library built on Temporal.',
  vault: 'Storage with schemas, TTL, and query building.',
  ward: 'Role-based access control (RBAC) system for permissions.',
  wayfinder: 'Routing library with nested routes and middleware support.',
};

export interface ReplCategory {
  functions: readonly string[];
  name: string;
}

export const ARSENAL_CATEGORIES: readonly ReplCategory[] = [
  {
    functions: [
      'chunk',
      'compact',
      'contains',
      'countBy',
      'difference',
      'drop',
      'dropLast',
      'filterMap',
      'first',
      'flatten',
      'groupBy',
      'indexBy',
      'intersection',
      'last',
      'partition',
      'replace',
      'rotate',
      'sample',
      'search',
      'sort',
      'take',
      'takeLast',
      'toggle',
      'union',
      'uniq',
      'unzip',
      'zip',
    ],
    name: 'Array',
  },
  {
    functions: [
      'abortable',
      'attempt',
      'defer',
      'parallel',
      'queue',
      'retry',
      'sleep',
      'timeout',
      'waitFor',
      'Scheduler',
      'polyfillScheduler',
    ],
    name: 'Async',
  },
  {
    functions: [
      'allOf',
      'anyOf',
      'assert',
      'assertAll',
      'compare',
      'compareBy',
      'compose',
      'constant',
      'curry',
      'debounce',
      'identity',
      'memo',
      'noneOf',
      'once',
      'partial',
      'pipe',
      'tap',
      'throttle',
    ],
    name: 'Function',
  },
  {
    functions: [
      'abs',
      'allocate',
      'average',
      'clamp',
      'gcd',
      'lcm',
      'lerp',
      'linspace',
      'max',
      'median',
      'min',
      'mod',
      'normalize',
      'percent',
      'range',
      'round',
      'standardDeviation',
      'sum',
      'variance',
    ],
    name: 'Math',
  },
  { functions: ['currency', 'exchange'], name: 'Money' },
  {
    functions: [
      'deepClone',
      'deepMerge',
      'defaults',
      'diff',
      'entries',
      'filterValues',
      'fromEntries',
      'get',
      'has',
      'invert',
      'keys',
      'mapKeys',
      'mapValues',
      'omit',
      'parseJSON',
      'pick',
      'prune',
      'shallowMerge',
      'stash',
      'values',
    ],
    name: 'Object',
  },
  { functions: ['draw', 'random', 'shuffle', 'uuid'], name: 'Random' },
  {
    functions: [
      'camelCase',
      'endsWith',
      'escape',
      'kebabCase',
      'pad',
      'pascalCase',
      'similarity',
      'snakeCase',
      'startsWith',
      'titleCase',
      'truncate',
      'unescape',
      'words',
    ],
    name: 'String',
  },
  {
    functions: [
      'is',
      'isArray',
      'isBoolean',
      'isDate',
      'isDefined',
      'isEmpty',
      'isEqual',
      'isFunction',
      'isGreaterThan',
      'isGreaterThanOrEqual',
      'isLessThan',
      'isLessThanOrEqual',
      'isMatch',
      'isNil',
      'isNumber',
      'isObject',
      'isPrimitive',
      'isPromise',
      'isRegex',
      'isString',
      'isWithin',
      'typeOf',
    ],
    name: 'Typed',
  },
];
