import type { WardPredicate, WardRuleInput } from './types';

import { WILDCARD } from './constants';

// ---------------------------------------------------------------------------
// Fluent rule builder
// ---------------------------------------------------------------------------

/**
 * Intermediate builder after `.allow()` or `.deny()` — captures the effect and roles.
 */
export type RoleStep<TAction extends string, TData> = {
  /** Set the resource this rule applies to. Use `WILDCARD` for any resource. */
  on(resource: string): ResourceStep<TAction, TData>;
};

/**
 * Intermediate builder after `.on()` — captures the resource.
 */
export type ResourceStep<TAction extends string, TData> = {
  /** Set one or more concrete actions, or `WILDCARD` for any action. */
  to(...actions: Array<TAction | typeof WILDCARD>): ActionStep<TAction, TData>;
};

/**
 * Final builder step — holds a complete rule definition and can add an optional
 * `when` predicate or a `priority`, or be converted to a `WardRule` array.
 */
export type ActionStep<TAction extends string, TData> = {
  /** Convert the current rule to a `WardRuleInput` array suitable for `createWard`. */
  build(): WardRuleInput<TAction, TData>[];
  /** Set the priority for all rules generated by this builder chain. */
  priority(n: number): ActionStep<TAction, TData>;
  /** Add a runtime predicate that must return `true` for the rule to apply. */
  when(predicate: WardPredicate<TData>): FinalStep<TAction, TData>;
};

/**
 * Final builder step after `.when()` — the predicate is set.
 */
export type FinalStep<TAction extends string, TData> = {
  /** Convert the current rule to a `WardRuleInput` array suitable for `createWard`. */
  build(): WardRuleInput<TAction, TData>[];
  /** Set the priority for all rules generated by this builder chain. */
  priority(n: number): FinalStep<TAction, TData>;
};

type PartialRule<TAction extends string, TData> = {
  actions?: Array<TAction | typeof WILDCARD>;
  effect: 'allow' | 'deny';
  predicate?: WardPredicate<TData>;
  priority?: number;
  resource?: string;
  role: string | readonly string[];
};

function makeActionStep<TAction extends string, TData>(
  partial: PartialRule<TAction, TData>,
): ActionStep<TAction, TData> {
  return {
    build() {
      return buildRules(partial);
    },
    priority(n) {
      return makeActionStep({ ...partial, priority: n });
    },
    when(predicate) {
      return makeFinalStep({ ...partial, predicate });
    },
  };
}

function makeFinalStep<TAction extends string, TData>(partial: PartialRule<TAction, TData>): FinalStep<TAction, TData> {
  return {
    build() {
      return buildRules(partial);
    },
    priority(n) {
      return makeFinalStep({ ...partial, priority: n });
    },
  };
}

function buildRules<TAction extends string, TData>(
  partial: PartialRule<TAction, TData>,
): WardRuleInput<TAction, TData>[] {
  const { actions = [WILDCARD], effect, predicate, priority, resource = WILDCARD, role } = partial;

  return actions.map((action) => {
    const ruleInput: WardRuleInput<TAction, TData> = { action, effect, resource, role };

    if (predicate) ruleInput.when = predicate;

    if (priority !== undefined) ruleInput.priority = priority;

    return ruleInput;
  });
}

/**
 * Fluent rule builder entry point.
 *
 * @example
 * ```ts
 * import { createWard, rule } from '@vielzeug/ward';
 *
 * const ward = createWard([
 *   ...rule<'read' | 'update'>().allow('viewer').on('posts').to('read').build(),
 *   ...rule<'read' | 'update'>().allow('editor').on('posts').to('read', 'update').build(),
 *   ...rule<'read' | 'update'>().allow('editor').on('posts').to('update').when(owns('authorId')).build(),
 * ]);
 * ```
 */
/**
 * Returns a `WardPredicate` that checks whether the data object's `attributeKey` field
 * matches the principal's `id`. Use to express ownership constraints.
 *
 * Must be used with a rule that requires authentication (non-`ANONYMOUS` role).
 * Predicates only execute for authenticated principals — pairing `owns` with an
 * `ANONYMOUS`-role rule produces a rule that can never match because the predicate
 * is skipped for unauthenticated requests.
 *
 * @example
 * ```ts
 * rule<PostAction, Post>().allow('editor').on('posts:*').to('update').when(owns('authorId')).build()
 * ```
 */
export function owns<TData = unknown>(attributeKey: keyof TData & string): WardPredicate<TData> {
  return ({ data, principal }) => {
    if (!data || typeof data !== 'object') return false;

    const value = (data as Record<string, unknown>)[attributeKey];

    return value === principal.id;
  };
}

/**
 * Type-safe rule slice factory for policy composition.
 * Returns the rules array unchanged; the value is purely in the generic type inference.
 * Use to define typed rule slices that can be spread into `createWard`.
 *
 * @example
 * ```ts
 * const postsRules = defineRules<PostAction, Post>([
 *   ...rule<PostAction>().allow('editor').on('posts:*').to('update').build(),
 * ]);
 * const ward = createWard([...postsRules, ...commentsRules]);
 * ```
 */
export function defineRules<TAction extends string = string, TData = unknown>(
  rules: readonly WardRuleInput<TAction, TData>[],
): readonly WardRuleInput<TAction, TData>[] {
  return rules;
}

export function rule<TAction extends string = string, TData = unknown>(): {
  allow(role: string | readonly string[]): RoleStep<TAction, TData>;
  deny(role: string | readonly string[]): RoleStep<TAction, TData>;
} {
  function makeRoleStep(effect: 'allow' | 'deny', role: string | readonly string[]): RoleStep<TAction, TData> {
    return {
      on(resource) {
        return {
          to(...actions) {
            return makeActionStep<TAction, TData>({ actions, effect, resource, role });
          },
        };
      },
    };
  }

  return {
    allow: (role) => makeRoleStep('allow', role),
    deny: (role) => makeRoleStep('deny', role),
  };
}
