import type { WardPredicate, WardRule } from './types';

import { WILDCARD } from './constants';

// ---------------------------------------------------------------------------
// Fluent rule builder
// ---------------------------------------------------------------------------

/**
 * Intermediate builder after `.allow()` or `.deny()` — captures the effect and roles.
 */
export type RoleStep<TAction extends string, TData> = {
  /** Set the resource this rule applies to. Use `WILDCARD` for any resource. */
  on(resource: string): ResourceStep<TAction, TData>;
};

/**
 * Intermediate builder after `.on()` — captures the resource.
 */
export type ResourceStep<TAction extends string, TData> = {
  /** Set one or more concrete actions, or `WILDCARD` for any action. */
  to(...actions: Array<TAction | typeof WILDCARD>): ActionStep<TAction, TData>;
};

/**
 * Final builder step — holds a complete rule definition and can add an optional
 * `when` predicate or a `priority`, or be converted to a `WardRule` array.
 */
export type ActionStep<TAction extends string, TData> = {
  /** Convert the current rule to a `WardRule` array suitable for `createWard`. */
  build(): WardRule<TAction, TData>[];
  /** Set the priority for all rules generated by this builder chain. */
  priority(n: number): ActionStep<TAction, TData>;
  /** Add a runtime predicate that must return `true` for the rule to apply. */
  when(predicate: WardPredicate<TData>): FinalStep<TAction, TData>;
};

/**
 * Final builder step after `.when()` — the predicate is set.
 */
export type FinalStep<TAction extends string, TData> = {
  /** Convert the current rule to a `WardRule` array suitable for `createWard`. */
  build(): WardRule<TAction, TData>[];
  /** Set the priority for all rules generated by this builder chain. */
  priority(n: number): FinalStep<TAction, TData>;
};

type PartialRule<TAction extends string, TData> = {
  actions?: Array<TAction | typeof WILDCARD>;
  effect: 'allow' | 'deny';
  predicate?: WardPredicate<TData>;
  priority?: number;
  resource?: string;
  role: string | readonly string[];
};

function makeActionStep<TAction extends string, TData>(
  partial: PartialRule<TAction, TData>,
): ActionStep<TAction, TData> {
  return {
    build() {
      return buildRules(partial);
    },
    priority(n) {
      return makeActionStep({ ...partial, priority: n });
    },
    when(predicate) {
      return makeFinalStep({ ...partial, predicate });
    },
  };
}

function makeFinalStep<TAction extends string, TData>(partial: PartialRule<TAction, TData>): FinalStep<TAction, TData> {
  return {
    build() {
      return buildRules(partial);
    },
    priority(n) {
      return makeFinalStep({ ...partial, priority: n });
    },
  };
}

function buildRules<TAction extends string, TData>(partial: PartialRule<TAction, TData>): WardRule<TAction, TData>[] {
  const { actions = [WILDCARD], effect, predicate, priority, resource = WILDCARD, role } = partial;

  return actions.map((action) => {
    const rule: WardRule<TAction, TData> = { action, effect, resource, role };

    if (predicate) rule.when = predicate;

    if (priority !== undefined) rule.priority = priority;

    return rule;
  });
}

/**
 * Fluent rule builder entry point.
 *
 * @example
 * ```ts
 * import { createWard, rule } from '@vielzeug/ward';
 *
 * const ward = createWard([
 *   ...rule<'read' | 'update'>().allow('viewer').on('posts').to('read').build(),
 *   ...rule<'read' | 'update'>().allow('editor').on('posts').to('read', 'update').build(),
 *   ...rule<'read' | 'update'>().allow('editor').on('posts').to('update').when(owns('authorId')).build(),
 * ]);
 * ```
 */
export function rule<TAction extends string = string, TData = unknown>(): {
  allow(role: string | readonly string[]): RoleStep<TAction, TData>;
  deny(role: string | readonly string[]): RoleStep<TAction, TData>;
} {
  function makeRoleStep(effect: 'allow' | 'deny', role: string | readonly string[]): RoleStep<TAction, TData> {
    return {
      on(resource) {
        return {
          to(...actions) {
            return makeActionStep<TAction, TData>({ actions, effect, resource, role });
          },
        };
      },
    };
  }

  return {
    allow: (role) => makeRoleStep('allow', role),
    deny: (role) => makeRoleStep('deny', role),
  };
}
